packages:
  00_substitutions: !include packages/00_substitutions.yaml
  01_base: !include packages/01_base.yaml
  10_state_globals: !include packages/10_state_globals.yaml
  20_hardware: !include packages/20_hardware.yaml
  30_sensors: !include packages/30_sensors.yaml
  40_faults: !include packages/40_faults.yaml
  50_comms_wifi: !include packages/50_comms_wifi.yaml
  51_comms_direct: !include packages/51_comms_direct.yaml
  60_services_scripts: !include packages/60_services_scripts.yaml
