// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef _WATERTANKSENSOR_UI_H
#define _WATERTANKSENSOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_boot.h"
#include "ui_home.h"
#include "ui_fresh.h"
#include "ui_Fresh_Faults.h"
#include "ui_Grey.h"
#include "ui_cydSettings.h"
#include "ui_Grey_Faults.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_592746240);   // assets/Two-gear-icon-removebg-preview-3.png
LV_IMG_DECLARE( ui_img_791807475);   // assets/_Pngtree_back_vector_icon_4279667-2-removebg-preview.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
