// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_BOOT_H
#define UI_BOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_boot
extern void ui_boot_screen_init(void);
extern void ui_boot_screen_destroy(void);
extern lv_obj_t *ui_boot;
extern void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_bootRoot;
extern lv_obj_t *ui_bootTitle;
extern lv_obj_t *ui_bootTitle3;
extern lv_obj_t *ui_bootwifipanel;
extern void ui_event_bootWifiButton( lv_event_t * e);
extern lv_obj_t *ui_bootWifiButton;
extern lv_obj_t *ui_wifibuttonlabel;
extern lv_obj_t *ui_wifidesclabel;
extern lv_obj_t *ui_bootDirectPanel;
extern lv_obj_t *ui_bootDirectButton;
extern lv_obj_t *ui_bootDirectLabel;
extern lv_obj_t *ui_directdesclabel;
extern lv_obj_t *ui_bootFirmwareLabel;
extern lv_obj_t *ui_overlayBootWifi;
extern lv_obj_t *ui_popupbootwifi;
extern lv_obj_t *ui_lblbootwifititle;
extern lv_obj_t *ui_lblbootwifidesc;
extern lv_obj_t *ui_ssid_container;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_bootWifissid;
extern lv_obj_t *ui_pwd_container1;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_bootWifipass;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_buttonBootWifiBack;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_buttonBootWifiNext;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_overlayBootDirect;
extern lv_obj_t *ui_popupbootwifi1;
extern lv_obj_t *ui_lbldirect;
extern lv_obj_t *ui_directcont1;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_bootdirectlist;
extern lv_obj_t *ui_lblBootDirectEmpty;
extern lv_obj_t *ui_directdevicetemplate;
extern lv_obj_t *ui_lbldirectdevnametemplate;
extern lv_obj_t *ui_lbldirectdeviptemplate;
extern lv_obj_t *ui_direct_buttons;
extern lv_obj_t *ui_buttonbootdirectback;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui_buttonbootdirectscan;
extern lv_obj_t *ui_Label30;
extern lv_obj_t *ui_overlayAssignDirectRole;
extern lv_obj_t *ui_contasign1;
extern lv_obj_t *ui_lblasign;
extern lv_obj_t *ui_contasign2;
extern lv_obj_t *ui_lvlassigndevicetitle;
extern lv_obj_t *ui_DirectAssignDeviceName;
extern lv_obj_t *ui_contasignbuttons;
extern lv_obj_t *ui_buttonbootasignfresh;
extern lv_obj_t *ui_Label28;
extern lv_obj_t *ui_buttonbootasignwaste;
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_contasignbuttons1;
extern lv_obj_t *ui_buttonbootasignfresh1;
extern lv_obj_t *ui_Label23;
extern lv_obj_t *ui_buttonbootasignwaste1;
extern lv_obj_t *ui_Label32;
// CUSTOM VARIABLES
extern lv_obj_t *uic_boot;
extern lv_obj_t *uic_bootRoot;
extern lv_obj_t *uic_bootTitle;
extern lv_obj_t *uic_bootTitle3;
extern lv_obj_t *uic_bootwifipanel;
extern lv_obj_t *uic_bootWifiButton;
extern lv_obj_t *uic_wifibuttonlabel;
extern lv_obj_t *uic_wifilabel;
extern lv_obj_t *uic_bootDirectPanel;
extern lv_obj_t *uic_bootDirectButton;
extern lv_obj_t *uic_bootDirectLabel;
extern lv_obj_t *uic_directlabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

