// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_BOOT_H
#define UI_BOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_boot
extern void ui_boot_screen_init(void);
extern void ui_boot_screen_destroy(void);
extern lv_obj_t *ui_boot;
extern lv_obj_t *ui_bootRoot;
extern lv_obj_t *ui_bootTitle;
extern lv_obj_t *ui_bootTitle3;
extern lv_obj_t *ui_bootwifipanel;
extern void ui_event_bootWifiButton( lv_event_t * e);
extern lv_obj_t *ui_bootWifiButton;
extern lv_obj_t *ui_wifibuttonlabel;
extern lv_obj_t *ui_wifidesclabel;
extern lv_obj_t *ui_bootDirectPanel;
extern lv_obj_t *ui_bootDirectButton;
extern lv_obj_t *ui_bootDirectLabel;
extern lv_obj_t *ui_directdesclabel;
extern lv_obj_t *ui_bootFirmwareLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_boot;
extern lv_obj_t *uic_bootRoot;
extern lv_obj_t *uic_bootTitle;
extern lv_obj_t *uic_bootTitle3;
extern lv_obj_t *uic_bootwifipanel;
extern lv_obj_t *uic_bootWifiButton;
extern lv_obj_t *uic_wifibuttonlabel;
extern lv_obj_t *uic_wifilabel;
extern lv_obj_t *uic_bootDirectPanel;
extern lv_obj_t *uic_bootDirectButton;
extern lv_obj_t *uic_bootDirectLabel;
extern lv_obj_t *uic_directlabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

