// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

// COMPONENT titlepanel

lv_obj_t *ui_titlepanel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_titlepanel;
cui_titlepanel = lv_obj_create(comp_parent);
lv_obj_set_height( cui_titlepanel, 50);
lv_obj_set_width( cui_titlepanel, lv_pct(100));
lv_obj_set_align( cui_titlepanel, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_titlepanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_titlepanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_homelabel;
cui_homelabel = lv_label_create(cui_titlepanel);
lv_obj_set_width( cui_homelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_homelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_homelabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_homelabel,"Home");
lv_obj_set_style_text_font(cui_homelabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ImgButton1;
cui_ImgButton1 = lv_imagebutton_create(cui_titlepanel);
lv_imagebutton_set_src(cui_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_592746240, NULL);
lv_obj_set_width( cui_ImgButton1, 46);
lv_obj_set_height( cui_ImgButton1, 48);
lv_obj_set_x( cui_ImgButton1, 84 );
lv_obj_set_y( cui_ImgButton1, -2 );
lv_obj_set_align( cui_ImgButton1, LV_ALIGN_CENTER );

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TITLEPANEL_NUM);
children[UI_COMP_TITLEPANEL_TITLEPANEL] = cui_titlepanel;
children[UI_COMP_TITLEPANEL_HOMELABEL] = cui_homelabel;
children[UI_COMP_TITLEPANEL_IMGBUTTON1] = cui_ImgButton1;
lv_obj_add_event_cb(cui_titlepanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_titlepanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_titlepanel_create_hook(cui_titlepanel);
return cui_titlepanel; 
}

