// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef _UI_COMP_TITLEPANEL_H
#define _UI_COMP_TITLEPANEL_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT titlepanel
#define UI_COMP_TITLEPANEL_TITLEPANEL 0
#define UI_COMP_TITLEPANEL_HOMELABEL 1
#define UI_COMP_TITLEPANEL_IMGBUTTON1 2
#define _UI_COMP_TITLEPANEL_NUM 3
lv_obj_t *ui_titlepanel_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
