// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

void btn_boot_wifi_event(lv_event_t * e)
{
	// Your code here
}
