// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_FRESHFAULTS_H
#define UI_FRESHFAULTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_freshfaults
extern void ui_freshfaults_screen_init(void);
extern void ui_freshfaults_screen_destroy(void);
extern lv_obj_t *ui_freshfaults;
extern lv_obj_t *ui_freshFaultPopupOverlay2;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_freshfaultscard;
extern lv_obj_t *ui_freshfaultsCodeLabel;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_freshfaultsdescription;
extern lv_obj_t *ui_freshfaultsCodeDescription;
extern lv_obj_t *ui_FreshPopupButtons2;
extern lv_obj_t *ui_freshfaultsBackButton;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_freshfaultsClearButton;
extern lv_obj_t *ui_Label18;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Fresh_Faults;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

