// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_FRESH_FAULTS_H
#define UI_FRESH_FAULTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Fresh_Faults
extern void ui_Fresh_Faults_screen_init(void);
extern void ui_Fresh_Faults_screen_destroy(void);
extern lv_obj_t *ui_Fresh_Faults;
extern lv_obj_t *ui_freshFaultPopupOverlay2;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_freshFaultPopupCard3;
extern lv_obj_t *ui_freshFaultCodeLabel2;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_freshFaultDescLabel2;
extern lv_obj_t *ui_FreshPopupButtons2;
extern void ui_event_freshFaultPopupCloseButton4( lv_event_t * e);
extern lv_obj_t *ui_freshFaultPopupCloseButton4;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_freshFaultClearButton2;
extern lv_obj_t *ui_Label18;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Fresh_Faults;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

