// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_FRESH_H
#define UI_FRESH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_fresh
extern void ui_fresh_screen_init(void);
extern void ui_fresh_screen_destroy(void);
extern lv_obj_t *ui_fresh;
extern lv_obj_t *ui_freshroot;
extern lv_obj_t *ui_freshheader;
extern lv_obj_t *ui_Label36;
extern lv_obj_t *ui_freshSettingsButton;
extern lv_obj_t *ui_freshBackButton;
extern lv_obj_t *ui_Label41;
extern lv_obj_t *ui_freshMainCard;
extern lv_obj_t *ui_freshLevelBar;
extern lv_obj_t *ui_freshLevelLabel;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_freshTempLabel;
extern lv_obj_t *ui_FreshStatusLabel;
extern lv_obj_t *ui_freshLeakLabel;
extern lv_obj_t *ui_freshFreezeLabel;
extern lv_obj_t *ui_freshlabels;
extern lv_obj_t *ui_Label25;
extern lv_obj_t *ui_Label26;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_freshFaultCont;
extern lv_obj_t *ui_Label27;
extern lv_obj_t *ui_freshFaultButton;
extern lv_obj_t *ui_freshFaultButtonLabel;
extern lv_obj_t *ui_freshControlPanel;
extern lv_obj_t *ui_freshFillButton;
extern lv_obj_t *ui_freshFillLabel;
extern lv_obj_t *ui_freshDrainButton;
extern lv_obj_t *ui_freshDrainLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_fresh;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

