// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

lv_obj_t *uic_Fresh_Faults;
lv_obj_t *ui_freshfaults = NULL;lv_obj_t *ui_freshFaultPopupOverlay2 = NULL;lv_obj_t *ui_Label20 = NULL;lv_obj_t *ui_freshfaultscard = NULL;lv_obj_t *ui_freshfaultsCodeLabel = NULL;lv_obj_t *ui_Label16 = NULL;lv_obj_t *ui_freshfaultsdescription = NULL;lv_obj_t *ui_freshfaultsCodeDescription = NULL;lv_obj_t *ui_FreshPopupButtons2 = NULL;lv_obj_t *ui_freshfaultsBackButton = NULL;lv_obj_t *ui_Label17 = NULL;lv_obj_t *ui_freshfaultsClearButton = NULL;lv_obj_t *ui_Label18 = NULL;
// event funtions

// build funtions

void ui_freshfaults_screen_init(void)
{
ui_freshfaults = lv_obj_create(NULL);
lv_obj_remove_flag( ui_freshfaults, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_freshfaults, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_freshfaults, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_black);

ui_freshFaultPopupOverlay2 = lv_obj_create(ui_freshfaults);
lv_obj_remove_style_all(ui_freshFaultPopupOverlay2);
lv_obj_set_width( ui_freshFaultPopupOverlay2, 227);
lv_obj_set_height( ui_freshFaultPopupOverlay2, 308);
lv_obj_set_x( ui_freshFaultPopupOverlay2, 1 );
lv_obj_set_y( ui_freshFaultPopupOverlay2, -3 );
lv_obj_set_align( ui_freshFaultPopupOverlay2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_freshFaultPopupOverlay2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshFaultPopupOverlay2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_freshFaultPopupOverlay2, lv_color_hex(0xD46B6B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_freshFaultPopupOverlay2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_freshFaultPopupOverlay2);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, 0 );
lv_obj_set_y( ui_Label20, -102 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"Fault Details");

ui_freshfaultscard = lv_obj_create(ui_freshFaultPopupOverlay2);
lv_obj_remove_style_all(ui_freshfaultscard);
lv_obj_set_width( ui_freshfaultscard, 200);
lv_obj_set_height( ui_freshfaultscard, 192);
lv_obj_set_x( ui_freshfaultscard, -1 );
lv_obj_set_y( ui_freshfaultscard, 10 );
lv_obj_set_align( ui_freshfaultscard, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_freshfaultscard, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshfaultscard, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freshfaultsCodeLabel = lv_label_create(ui_freshfaultscard);
lv_obj_set_width( ui_freshfaultsCodeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshfaultsCodeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_freshfaultsCodeLabel, 0 );
lv_obj_set_y( ui_freshfaultsCodeLabel, -86 );
lv_obj_set_align( ui_freshfaultsCodeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshfaultsCodeLabel,"test");

ui_Label16 = lv_label_create(ui_freshfaultscard);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, 0 );
lv_obj_set_y( ui_Label16, -60 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Description:");

ui_freshfaultsdescription = lv_obj_create(ui_freshfaultscard);
lv_obj_remove_style_all(ui_freshfaultsdescription);
lv_obj_set_width( ui_freshfaultsdescription, 170);
lv_obj_set_height( ui_freshfaultsdescription, 122);
lv_obj_set_x( ui_freshfaultsdescription, 0 );
lv_obj_set_y( ui_freshfaultsdescription, 14 );
lv_obj_set_align( ui_freshfaultsdescription, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_freshfaultsdescription, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_freshfaultsCodeDescription = lv_label_create(ui_freshfaultsdescription);
lv_obj_set_width( ui_freshfaultsCodeDescription, lv_pct(100));
lv_obj_set_height( ui_freshfaultsCodeDescription, lv_pct(100));
lv_obj_set_align( ui_freshfaultsCodeDescription, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshfaultsCodeDescription,"\nNo Active Fault");
lv_obj_set_style_text_align(ui_freshfaultsCodeDescription, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FreshPopupButtons2 = lv_obj_create(ui_freshFaultPopupOverlay2);
lv_obj_remove_style_all(ui_FreshPopupButtons2);
lv_obj_set_width( ui_FreshPopupButtons2, 222);
lv_obj_set_height( ui_FreshPopupButtons2, 50);
lv_obj_set_x( ui_FreshPopupButtons2, 0 );
lv_obj_set_y( ui_FreshPopupButtons2, 125 );
lv_obj_set_align( ui_FreshPopupButtons2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_FreshPopupButtons2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_FreshPopupButtons2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_FreshPopupButtons2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_pad_row(ui_FreshPopupButtons2, 10, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_FreshPopupButtons2, 10, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_freshfaultsBackButton = lv_button_create(ui_FreshPopupButtons2);
lv_obj_set_width( ui_freshfaultsBackButton, 100);
lv_obj_set_height( ui_freshfaultsBackButton, 40);
lv_obj_set_x( ui_freshfaultsBackButton, -51 );
lv_obj_set_y( ui_freshfaultsBackButton, 116 );
lv_obj_set_align( ui_freshfaultsBackButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshfaultsBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshfaultsBackButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label17 = lv_label_create(ui_freshfaultsBackButton);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Back");

ui_freshfaultsClearButton = lv_button_create(ui_FreshPopupButtons2);
lv_obj_set_width( ui_freshfaultsClearButton, 100);
lv_obj_set_height( ui_freshfaultsClearButton, 40);
lv_obj_set_x( ui_freshfaultsClearButton, 37 );
lv_obj_set_y( ui_freshfaultsClearButton, 67 );
lv_obj_set_align( ui_freshfaultsClearButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshfaultsClearButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshfaultsClearButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label18 = lv_label_create(ui_freshfaultsClearButton);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"Clear");

uic_Fresh_Faults = ui_freshfaults;

}

void ui_freshfaults_screen_destroy(void)
{
   if (ui_freshfaults) lv_obj_del(ui_freshfaults);

// NULL screen variables
uic_Fresh_Faults= NULL;
ui_freshfaults= NULL;
ui_freshFaultPopupOverlay2= NULL;
ui_Label20= NULL;
ui_freshfaultscard= NULL;
ui_freshfaultsCodeLabel= NULL;
ui_Label16= NULL;
ui_freshfaultsdescription= NULL;
ui_freshfaultsCodeDescription= NULL;
ui_FreshPopupButtons2= NULL;
ui_freshfaultsBackButton= NULL;
ui_Label17= NULL;
ui_freshfaultsClearButton= NULL;
ui_Label18= NULL;

}
