// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

lv_obj_t *uic_fresh;
lv_obj_t *ui_fresh = NULL;lv_obj_t *ui_freshroot = NULL;lv_obj_t *ui_hometitelpanel1 = NULL;lv_obj_t *ui_ImgButton4 = NULL;lv_obj_t *ui_freshMainCard = NULL;lv_obj_t *ui_freshLevelBar = NULL;lv_obj_t *ui_freshLevelLabel = NULL;lv_obj_t *ui_Container10 = NULL;lv_obj_t *ui_freshTempLabel = NULL;lv_obj_t *ui_FreshStatusLabel = NULL;lv_obj_t *ui_freshLeakLabel = NULL;lv_obj_t *ui_freshFreezeLabel = NULL;lv_obj_t *ui_Container11 = NULL;lv_obj_t *ui_Label25 = NULL;lv_obj_t *ui_Label26 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_freshFaultCont = NULL;lv_obj_t *ui_Label27 = NULL;lv_obj_t *ui_freshFaultCodeButton = NULL;lv_obj_t *ui_freshFaultCodeButtonLabel = NULL;lv_obj_t *ui_freshControlPanel = NULL;lv_obj_t *ui_freshFillButton = NULL;lv_obj_t *ui_freshFillLabel = NULL;lv_obj_t *ui_freshDrainButton = NULL;lv_obj_t *ui_freshDrainLabel = NULL;
// event funtions
void ui_event_ImgButton4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_home_screen_init);
}
}

void ui_event_freshFaultCodeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Fresh_Faults, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Fresh_Faults_screen_init);
}
}

// build funtions

void ui_fresh_screen_init(void)
{
ui_fresh = lv_obj_create(NULL);
lv_obj_remove_flag( ui_fresh, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_fresh, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_fresh, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_black);

ui_freshroot = lv_obj_create(ui_fresh);
lv_obj_remove_style_all(ui_freshroot);
lv_obj_set_width( ui_freshroot, 240);
lv_obj_set_height( ui_freshroot, 320);
lv_obj_set_align( ui_freshroot, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_freshroot,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_freshroot, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_freshroot, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_freshroot, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_freshroot, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hometitelpanel1 = ui_titlepanel_create(ui_freshroot);
lv_obj_set_x( ui_hometitelpanel1, 0 );
lv_obj_set_y( ui_hometitelpanel1, 0 );
lv_obj_set_style_bg_color(ui_hometitelpanel1, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_hometitelpanel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_label_set_text(ui_comp_get_child(ui_hometitelpanel1, UI_COMP_TITLEPANEL_HOMELABEL),"Fresh");

ui_ImgButton4 = lv_imagebutton_create(ui_hometitelpanel1);
lv_imagebutton_set_src(ui_ImgButton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_791807475, NULL);
lv_imagebutton_set_src(ui_ImgButton4, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_791807475, NULL);
lv_obj_set_width( ui_ImgButton4, 60);
lv_obj_set_height( ui_ImgButton4, 60);
lv_obj_set_x( ui_ImgButton4, -90 );
lv_obj_set_y( ui_ImgButton4, 0 );
lv_obj_set_align( ui_ImgButton4, LV_ALIGN_CENTER );

lv_obj_move_to_index(ui_ImgButton4,2);
ui_freshMainCard = lv_obj_create(ui_freshroot);
lv_obj_set_width( ui_freshMainCard, 224);
lv_obj_set_height( ui_freshMainCard, 180);
lv_obj_set_align( ui_freshMainCard, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_freshMainCard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshMainCard, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_freshMainCard, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_freshMainCard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freshLevelBar = lv_bar_create(ui_freshMainCard);
lv_bar_set_value(ui_freshLevelBar,75,LV_ANIM_OFF);
lv_bar_set_start_value(ui_freshLevelBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_freshLevelBar, 120);
lv_obj_set_height( ui_freshLevelBar, 50);
lv_obj_set_x( ui_freshLevelBar, 106 );
lv_obj_set_y( ui_freshLevelBar, 69 );
lv_obj_set_align( ui_freshLevelBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_freshLevelBar, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_rotation(ui_freshLevelBar, 2700, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_freshLevelBar, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_freshLevelBar,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_freshLevelBar, lv_obj_get_style_pad_right(ui_freshLevelBar,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_freshLevelLabel = lv_label_create(ui_freshMainCard);
lv_obj_set_width( ui_freshLevelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshLevelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_freshLevelLabel, 71 );
lv_obj_set_y( ui_freshLevelLabel, 63 );
lv_obj_set_align( ui_freshLevelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshLevelLabel,"75%");

ui_Container10 = lv_obj_create(ui_freshMainCard);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_width( ui_Container10, 60);
lv_obj_set_height( ui_Container10, 120);
lv_obj_set_x( ui_Container10, 0 );
lv_obj_set_y( ui_Container10, -15 );
lv_obj_set_align( ui_Container10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container10,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_freshTempLabel = lv_label_create(ui_Container10);
lv_obj_set_width( ui_freshTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_freshTempLabel, 4 );
lv_obj_set_y( ui_freshTempLabel, -61 );
lv_obj_set_align( ui_freshTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshTempLabel,"22.4 °C");

ui_FreshStatusLabel = lv_label_create(ui_Container10);
lv_obj_set_width( ui_FreshStatusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FreshStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FreshStatusLabel, 4 );
lv_obj_set_y( ui_FreshStatusLabel, -24 );
lv_obj_set_align( ui_FreshStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_FreshStatusLabel,"OK");

ui_freshLeakLabel = lv_label_create(ui_Container10);
lv_obj_set_width( ui_freshLeakLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshLeakLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_freshLeakLabel, 4 );
lv_obj_set_y( ui_freshLeakLabel, -61 );
lv_obj_set_align( ui_freshLeakLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshLeakLabel,"Dry");

ui_freshFreezeLabel = lv_label_create(ui_Container10);
lv_obj_set_width( ui_freshFreezeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshFreezeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_freshFreezeLabel, 4 );
lv_obj_set_y( ui_freshFreezeLabel, -61 );
lv_obj_set_align( ui_freshFreezeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshFreezeLabel,"Off");

ui_Container11 = lv_obj_create(ui_freshMainCard);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_width( ui_Container11, 60);
lv_obj_set_height( ui_Container11, 120);
lv_obj_set_x( ui_Container11, -70 );
lv_obj_set_y( ui_Container11, -15 );
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container11,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label25 = lv_label_create(ui_Container11);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label25, -65 );
lv_obj_set_y( ui_Label25, -61 );
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"Temp");

ui_Label26 = lv_label_create(ui_Container11);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label26, -63 );
lv_obj_set_y( ui_Label26, -25 );
lv_obj_set_align( ui_Label26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label26,"Status");

ui_Label1 = lv_label_create(ui_Container11);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -65 );
lv_obj_set_y( ui_Label1, -61 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Leak");

ui_Label2 = lv_label_create(ui_Container11);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -65 );
lv_obj_set_y( ui_Label2, -61 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Freeze");

ui_freshFaultCont = lv_obj_create(ui_freshMainCard);
lv_obj_remove_style_all(ui_freshFaultCont);
lv_obj_set_width( ui_freshFaultCont, 168);
lv_obj_set_height( ui_freshFaultCont, 36);
lv_obj_set_x( ui_freshFaultCont, -33 );
lv_obj_set_y( ui_freshFaultCont, 57 );
lv_obj_set_align( ui_freshFaultCont, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_freshFaultCont,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_freshFaultCont, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_freshFaultCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label27 = lv_label_create(ui_freshFaultCont);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"Fault");

ui_freshFaultCodeButton = lv_button_create(ui_freshFaultCont);
lv_obj_set_width( ui_freshFaultCodeButton, 50);
lv_obj_set_height( ui_freshFaultCodeButton, 30);
lv_obj_set_x( ui_freshFaultCodeButton, 0 );
lv_obj_set_y( ui_freshFaultCodeButton, 11 );
lv_obj_set_align( ui_freshFaultCodeButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshFaultCodeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshFaultCodeButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_freshFaultCodeButtonLabel = lv_label_create(ui_freshFaultCodeButton);
lv_obj_set_width( ui_freshFaultCodeButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshFaultCodeButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_freshFaultCodeButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshFaultCodeButtonLabel,"0");

ui_freshControlPanel = lv_obj_create(ui_freshroot);
lv_obj_set_width( ui_freshControlPanel, 224);
lv_obj_set_height( ui_freshControlPanel, 60);
lv_obj_set_align( ui_freshControlPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_freshControlPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_freshControlPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_freshControlPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshControlPanel, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_freshControlPanel, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_freshControlPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freshFillButton = lv_button_create(ui_freshControlPanel);
lv_obj_set_width( ui_freshFillButton, 100);
lv_obj_set_height( ui_freshFillButton, 50);
lv_obj_set_align( ui_freshFillButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshFillButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshFillButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshFillButton, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freshFillLabel = lv_label_create(ui_freshFillButton);
lv_obj_set_width( ui_freshFillLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshFillLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_freshFillLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshFillLabel,"FILL");
lv_obj_set_style_text_font(ui_freshFillLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freshDrainButton = lv_button_create(ui_freshControlPanel);
lv_obj_set_width( ui_freshDrainButton, 100);
lv_obj_set_height( ui_freshDrainButton, 50);
lv_obj_set_align( ui_freshDrainButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshDrainButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshDrainButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshDrainButton, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freshDrainLabel = lv_label_create(ui_freshDrainButton);
lv_obj_set_width( ui_freshDrainLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshDrainLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_freshDrainLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshDrainLabel,"DRAIN");
lv_obj_set_style_text_font(ui_freshDrainLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_freshFaultCodeButton, ui_event_freshFaultCodeButton, LV_EVENT_ALL, NULL);
uic_fresh = ui_fresh;

}

void ui_fresh_screen_destroy(void)
{
   if (ui_fresh) lv_obj_del(ui_fresh);

// NULL screen variables
uic_fresh= NULL;
ui_fresh= NULL;
ui_freshroot= NULL;
ui_hometitelpanel1= NULL;
ui_ImgButton4= NULL;
ui_freshMainCard= NULL;
ui_freshLevelBar= NULL;
ui_freshLevelLabel= NULL;
ui_Container10= NULL;
ui_freshTempLabel= NULL;
ui_FreshStatusLabel= NULL;
ui_freshLeakLabel= NULL;
ui_freshFreezeLabel= NULL;
ui_Container11= NULL;
ui_Label25= NULL;
ui_Label26= NULL;
ui_Label1= NULL;
ui_Label2= NULL;
ui_freshFaultCont= NULL;
ui_Label27= NULL;
ui_freshFaultCodeButton= NULL;
ui_freshFaultCodeButtonLabel= NULL;
ui_freshControlPanel= NULL;
ui_freshFillButton= NULL;
ui_freshFillLabel= NULL;
ui_freshDrainButton= NULL;
ui_freshDrainLabel= NULL;

}
