// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

lv_obj_t *uic_Fresh_Faults;
lv_obj_t *ui_Fresh_Faults = NULL;lv_obj_t *ui_freshFaultPopupOverlay2 = NULL;lv_obj_t *ui_Label20 = NULL;lv_obj_t *ui_freshFaultPopupCard3 = NULL;lv_obj_t *ui_freshFaultCodeLabel2 = NULL;lv_obj_t *ui_Label16 = NULL;lv_obj_t *ui_Container5 = NULL;lv_obj_t *ui_freshFaultDescLabel2 = NULL;lv_obj_t *ui_FreshPopupButtons2 = NULL;lv_obj_t *ui_freshFaultPopupCloseButton4 = NULL;lv_obj_t *ui_Label17 = NULL;lv_obj_t *ui_freshFaultClearButton2 = NULL;lv_obj_t *ui_Label18 = NULL;
// event funtions
void ui_event_freshFaultPopupCloseButton4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_fresh, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_fresh_screen_init);
}
}

// build funtions

void ui_Fresh_Faults_screen_init(void)
{
ui_Fresh_Faults = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Fresh_Faults, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_freshFaultPopupOverlay2 = lv_obj_create(ui_Fresh_Faults);
lv_obj_remove_style_all(ui_freshFaultPopupOverlay2);
lv_obj_set_width( ui_freshFaultPopupOverlay2, 227);
lv_obj_set_height( ui_freshFaultPopupOverlay2, 308);
lv_obj_set_x( ui_freshFaultPopupOverlay2, 1 );
lv_obj_set_y( ui_freshFaultPopupOverlay2, -3 );
lv_obj_set_align( ui_freshFaultPopupOverlay2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_freshFaultPopupOverlay2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshFaultPopupOverlay2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_freshFaultPopupOverlay2, lv_color_hex(0xD46B6B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_freshFaultPopupOverlay2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_freshFaultPopupOverlay2);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, 0 );
lv_obj_set_y( ui_Label20, -102 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"Fault Details");

ui_freshFaultPopupCard3 = lv_obj_create(ui_freshFaultPopupOverlay2);
lv_obj_remove_style_all(ui_freshFaultPopupCard3);
lv_obj_set_width( ui_freshFaultPopupCard3, 200);
lv_obj_set_height( ui_freshFaultPopupCard3, 192);
lv_obj_set_x( ui_freshFaultPopupCard3, -1 );
lv_obj_set_y( ui_freshFaultPopupCard3, 10 );
lv_obj_set_align( ui_freshFaultPopupCard3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_freshFaultPopupCard3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshFaultPopupCard3, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freshFaultCodeLabel2 = lv_label_create(ui_freshFaultPopupCard3);
lv_obj_set_width( ui_freshFaultCodeLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshFaultCodeLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_freshFaultCodeLabel2, 0 );
lv_obj_set_y( ui_freshFaultCodeLabel2, -86 );
lv_obj_set_align( ui_freshFaultCodeLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshFaultCodeLabel2,"0");

ui_Label16 = lv_label_create(ui_freshFaultPopupCard3);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, 0 );
lv_obj_set_y( ui_Label16, -60 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Description:");

ui_Container5 = lv_obj_create(ui_freshFaultPopupCard3);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 170);
lv_obj_set_height( ui_Container5, 122);
lv_obj_set_x( ui_Container5, 0 );
lv_obj_set_y( ui_Container5, 14 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_freshFaultDescLabel2 = lv_label_create(ui_Container5);
lv_obj_set_width( ui_freshFaultDescLabel2, lv_pct(100));
lv_obj_set_height( ui_freshFaultDescLabel2, lv_pct(100));
lv_obj_set_align( ui_freshFaultDescLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshFaultDescLabel2,"\nNo Active Fault");
lv_obj_set_style_text_align(ui_freshFaultDescLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FreshPopupButtons2 = lv_obj_create(ui_freshFaultPopupOverlay2);
lv_obj_remove_style_all(ui_FreshPopupButtons2);
lv_obj_set_width( ui_FreshPopupButtons2, 222);
lv_obj_set_height( ui_FreshPopupButtons2, 50);
lv_obj_set_x( ui_FreshPopupButtons2, 0 );
lv_obj_set_y( ui_FreshPopupButtons2, 125 );
lv_obj_set_align( ui_FreshPopupButtons2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_FreshPopupButtons2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_FreshPopupButtons2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_FreshPopupButtons2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_pad_row(ui_FreshPopupButtons2, 10, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_FreshPopupButtons2, 10, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_freshFaultPopupCloseButton4 = lv_button_create(ui_FreshPopupButtons2);
lv_obj_set_width( ui_freshFaultPopupCloseButton4, 100);
lv_obj_set_height( ui_freshFaultPopupCloseButton4, 40);
lv_obj_set_x( ui_freshFaultPopupCloseButton4, -51 );
lv_obj_set_y( ui_freshFaultPopupCloseButton4, 116 );
lv_obj_set_align( ui_freshFaultPopupCloseButton4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshFaultPopupCloseButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshFaultPopupCloseButton4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label17 = lv_label_create(ui_freshFaultPopupCloseButton4);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Back");

ui_freshFaultClearButton2 = lv_button_create(ui_FreshPopupButtons2);
lv_obj_set_width( ui_freshFaultClearButton2, 100);
lv_obj_set_height( ui_freshFaultClearButton2, 40);
lv_obj_set_x( ui_freshFaultClearButton2, 37 );
lv_obj_set_y( ui_freshFaultClearButton2, 67 );
lv_obj_set_align( ui_freshFaultClearButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshFaultClearButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshFaultClearButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label18 = lv_label_create(ui_freshFaultClearButton2);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"Clear");

lv_obj_add_event_cb(ui_freshFaultPopupCloseButton4, ui_event_freshFaultPopupCloseButton4, LV_EVENT_ALL, NULL);
uic_Fresh_Faults = ui_Fresh_Faults;

}

void ui_Fresh_Faults_screen_destroy(void)
{
   if (ui_Fresh_Faults) lv_obj_del(ui_Fresh_Faults);

// NULL screen variables
uic_Fresh_Faults= NULL;
ui_Fresh_Faults= NULL;
ui_freshFaultPopupOverlay2= NULL;
ui_Label20= NULL;
ui_freshFaultPopupCard3= NULL;
ui_freshFaultCodeLabel2= NULL;
ui_Label16= NULL;
ui_Container5= NULL;
ui_freshFaultDescLabel2= NULL;
ui_FreshPopupButtons2= NULL;
ui_freshFaultPopupCloseButton4= NULL;
ui_Label17= NULL;
ui_freshFaultClearButton2= NULL;
ui_Label18= NULL;

}
