// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_FRESHSETTINGS_H
#define UI_FRESHSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_freshsettings
extern void ui_freshsettings_screen_init(void);
extern void ui_freshsettings_screen_destroy(void);
extern lv_obj_t *ui_freshsettings;
extern lv_obj_t *ui_freshsettingsroot;
extern lv_obj_t *ui_freshsettingsheader;
extern lv_obj_t *ui_Label43;
extern lv_obj_t *ui_freshsettingsBackButton;
extern lv_obj_t *ui_Label40;
extern lv_obj_t *ui_freshsettingsMainCard;
extern lv_obj_t *ui_freshsettingslabels;
extern lv_obj_t *ui_Label38;
extern lv_obj_t *ui_Label49;
extern lv_obj_t *ui_Label50;
extern lv_obj_t *ui_Label46;
extern lv_obj_t *ui_Label47;
extern lv_obj_t *ui_Label48;
extern lv_obj_t *ui_Label52;
extern lv_obj_t *ui_Label53;
extern lv_obj_t *ui_freshsettingsControls;
extern lv_obj_t *ui_freshsettingsFillLevelButton;
extern lv_obj_t *ui_freshsettingsFillStopLevelLabel;
extern lv_obj_t *ui_freshsettingsSetFullButton;
extern lv_obj_t *ui_freshsettingsFullVoltage;
extern lv_obj_t *ui_freshsettingsSetEmptyButton;
extern lv_obj_t *ui_freshsettingsEmptyVoltage;
extern lv_obj_t *ui_freshsettingsFreezeProtection;
extern lv_obj_t *ui_freshsettingsRestart;
extern lv_obj_t *ui_freshsettingsSafetyOveride;
extern lv_obj_t *ui_freshsettingsValveOveride;
extern lv_obj_t *ui_freshsettingsDiagnostic;
extern lv_obj_t *ui_freshsettingsFillOverlay;
extern lv_obj_t *ui_freshsettingsOverlayFillSlider;
extern lv_obj_t *ui_freshsettingsOverlayFillPercentage;
extern lv_obj_t *ui_freshsettingsOverlayBackButton;
extern lv_obj_t *ui_Label51;
extern lv_obj_t *ui_freshsettingsDiagnosticOverlay;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label54;
extern lv_obj_t *ui_Label55;
extern lv_obj_t *ui_Label56;
extern lv_obj_t *ui_Label57;
extern lv_obj_t *ui_Label58;
extern lv_obj_t *ui_Label59;
extern lv_obj_t *ui_Label60;
extern lv_obj_t *ui_Label61;
extern lv_obj_t *ui_Label62;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_freshsettingsdiagoverlayIP;
extern lv_obj_t *ui_freshsettingsdiagoverlayID;
extern lv_obj_t *ui_freshsettingsdiagoverlayMAC;
extern lv_obj_t *ui_freshsettingsdiagoverlayStatus;
extern lv_obj_t *ui_freshsettingsdiagoverlayRole;
extern lv_obj_t *ui_freshsettingsdiagoverlayUptime;
extern lv_obj_t *ui_freshsettingsdiagoverlaySignal;
extern lv_obj_t *ui_freshsettingsdiagoverlayVersion;
extern lv_obj_t *ui_freshsettingDiagnosticOverlayBackButton;
extern lv_obj_t *ui_Label63;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

