// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

lv_obj_t *ui_Grey = NULL;lv_obj_t *ui_freshroot1 = NULL;lv_obj_t *ui_hometitelpanel2 = NULL;lv_obj_t *ui_ImgButton2 = NULL;lv_obj_t *ui_freshMainCard1 = NULL;lv_obj_t *ui_greyLevelBar = NULL;lv_obj_t *ui_greyLevelLabel = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_greyTempLabel = NULL;lv_obj_t *ui_greyStatusLabel = NULL;lv_obj_t *ui_greyLeakLabel = NULL;lv_obj_t *ui_greyFreezeLabel = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_freshFaultCont1 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_freshFaultCodeButton1 = NULL;lv_obj_t *ui_greyFaultCodeButtonLabel = NULL;lv_obj_t *ui_freshControlPanel1 = NULL;lv_obj_t *ui_freshDrainButton1 = NULL;lv_obj_t *ui_freshDrainLabel1 = NULL;
// event funtions
void ui_event_ImgButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home_screen_init);
}
}

void ui_event_freshFaultCodeButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Grey_Faults, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Grey_Faults_screen_init);
}
}

// build funtions

void ui_Grey_screen_init(void)
{
ui_Grey = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Grey, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Grey, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_Grey, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_black);

ui_freshroot1 = lv_obj_create(ui_Grey);
lv_obj_remove_style_all(ui_freshroot1);
lv_obj_set_width( ui_freshroot1, 240);
lv_obj_set_height( ui_freshroot1, 320);
lv_obj_set_align( ui_freshroot1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_freshroot1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_freshroot1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_freshroot1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_freshroot1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_freshroot1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hometitelpanel2 = ui_titlepanel_create(ui_freshroot1);
lv_obj_set_x( ui_hometitelpanel2, 0 );
lv_obj_set_y( ui_hometitelpanel2, 0 );
lv_obj_set_style_bg_color(ui_hometitelpanel2, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_hometitelpanel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_label_set_text(ui_comp_get_child(ui_hometitelpanel2, UI_COMP_TITLEPANEL_HOMELABEL),"Waste");

ui_ImgButton2 = lv_imagebutton_create(ui_hometitelpanel2);
lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_791807475, NULL);
lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_791807475, NULL);
lv_obj_set_width( ui_ImgButton2, 60);
lv_obj_set_height( ui_ImgButton2, 60);
lv_obj_set_x( ui_ImgButton2, -90 );
lv_obj_set_y( ui_ImgButton2, 0 );
lv_obj_set_align( ui_ImgButton2, LV_ALIGN_CENTER );

lv_obj_move_to_index(ui_ImgButton2,2);
ui_freshMainCard1 = lv_obj_create(ui_freshroot1);
lv_obj_set_width( ui_freshMainCard1, 224);
lv_obj_set_height( ui_freshMainCard1, 180);
lv_obj_set_align( ui_freshMainCard1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_freshMainCard1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshMainCard1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_freshMainCard1, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_freshMainCard1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_greyLevelBar = lv_bar_create(ui_freshMainCard1);
lv_bar_set_value(ui_greyLevelBar,75,LV_ANIM_OFF);
lv_bar_set_start_value(ui_greyLevelBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_greyLevelBar, 120);
lv_obj_set_height( ui_greyLevelBar, 50);
lv_obj_set_x( ui_greyLevelBar, 106 );
lv_obj_set_y( ui_greyLevelBar, 69 );
lv_obj_set_align( ui_greyLevelBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_greyLevelBar, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_rotation(ui_greyLevelBar, 2700, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_greyLevelBar, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_greyLevelBar,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_greyLevelBar, lv_obj_get_style_pad_right(ui_greyLevelBar,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_greyLevelLabel = lv_label_create(ui_freshMainCard1);
lv_obj_set_width( ui_greyLevelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_greyLevelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_greyLevelLabel, 71 );
lv_obj_set_y( ui_greyLevelLabel, 63 );
lv_obj_set_align( ui_greyLevelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_greyLevelLabel,"75%");

ui_Container1 = lv_obj_create(ui_freshMainCard1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 60);
lv_obj_set_height( ui_Container1, 120);
lv_obj_set_x( ui_Container1, 0 );
lv_obj_set_y( ui_Container1, -15 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_greyTempLabel = lv_label_create(ui_Container1);
lv_obj_set_width( ui_greyTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_greyTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_greyTempLabel, 4 );
lv_obj_set_y( ui_greyTempLabel, -61 );
lv_obj_set_align( ui_greyTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_greyTempLabel,"22.4 °C");

ui_greyStatusLabel = lv_label_create(ui_Container1);
lv_obj_set_width( ui_greyStatusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_greyStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_greyStatusLabel, 4 );
lv_obj_set_y( ui_greyStatusLabel, -24 );
lv_obj_set_align( ui_greyStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_greyStatusLabel,"OK");

ui_greyLeakLabel = lv_label_create(ui_Container1);
lv_obj_set_width( ui_greyLeakLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_greyLeakLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_greyLeakLabel, 4 );
lv_obj_set_y( ui_greyLeakLabel, -61 );
lv_obj_set_align( ui_greyLeakLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_greyLeakLabel,"Dry");

ui_greyFreezeLabel = lv_label_create(ui_Container1);
lv_obj_set_width( ui_greyFreezeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_greyFreezeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_greyFreezeLabel, 4 );
lv_obj_set_y( ui_greyFreezeLabel, -61 );
lv_obj_set_align( ui_greyFreezeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_greyFreezeLabel,"Off");

ui_Container2 = lv_obj_create(ui_freshMainCard1);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 60);
lv_obj_set_height( ui_Container2, 120);
lv_obj_set_x( ui_Container2, -70 );
lv_obj_set_y( ui_Container2, -15 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -65 );
lv_obj_set_y( ui_Label3, -61 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Temp");

ui_Label5 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -63 );
lv_obj_set_y( ui_Label5, -25 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Status");

ui_Label6 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -65 );
lv_obj_set_y( ui_Label6, -61 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Leak");

ui_Label7 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -65 );
lv_obj_set_y( ui_Label7, -61 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Freeze");

ui_freshFaultCont1 = lv_obj_create(ui_freshMainCard1);
lv_obj_remove_style_all(ui_freshFaultCont1);
lv_obj_set_width( ui_freshFaultCont1, 168);
lv_obj_set_height( ui_freshFaultCont1, 36);
lv_obj_set_x( ui_freshFaultCont1, -33 );
lv_obj_set_y( ui_freshFaultCont1, 57 );
lv_obj_set_align( ui_freshFaultCont1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_freshFaultCont1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_freshFaultCont1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_freshFaultCont1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_freshFaultCont1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Fault");

ui_freshFaultCodeButton1 = lv_button_create(ui_freshFaultCont1);
lv_obj_set_width( ui_freshFaultCodeButton1, 50);
lv_obj_set_height( ui_freshFaultCodeButton1, 30);
lv_obj_set_x( ui_freshFaultCodeButton1, 0 );
lv_obj_set_y( ui_freshFaultCodeButton1, 11 );
lv_obj_set_align( ui_freshFaultCodeButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshFaultCodeButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshFaultCodeButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_greyFaultCodeButtonLabel = lv_label_create(ui_freshFaultCodeButton1);
lv_obj_set_width( ui_greyFaultCodeButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_greyFaultCodeButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_greyFaultCodeButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_greyFaultCodeButtonLabel,"0");

ui_freshControlPanel1 = lv_obj_create(ui_freshroot1);
lv_obj_set_width( ui_freshControlPanel1, 224);
lv_obj_set_height( ui_freshControlPanel1, 60);
lv_obj_set_align( ui_freshControlPanel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_freshControlPanel1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_freshControlPanel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_freshControlPanel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshControlPanel1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_freshControlPanel1, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_freshControlPanel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freshDrainButton1 = lv_button_create(ui_freshControlPanel1);
lv_obj_set_width( ui_freshDrainButton1, 207);
lv_obj_set_height( ui_freshDrainButton1, 50);
lv_obj_set_align( ui_freshDrainButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshDrainButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshDrainButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshDrainButton1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freshDrainLabel1 = lv_label_create(ui_freshDrainButton1);
lv_obj_set_width( ui_freshDrainLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_freshDrainLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_freshDrainLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_freshDrainLabel1,"DRAIN");
lv_obj_set_style_text_font(ui_freshDrainLabel1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_freshFaultCodeButton1, ui_event_freshFaultCodeButton1, LV_EVENT_ALL, NULL);

}

void ui_Grey_screen_destroy(void)
{
   if (ui_Grey) lv_obj_del(ui_Grey);

// NULL screen variables
ui_Grey= NULL;
ui_freshroot1= NULL;
ui_hometitelpanel2= NULL;
ui_ImgButton2= NULL;
ui_freshMainCard1= NULL;
ui_greyLevelBar= NULL;
ui_greyLevelLabel= NULL;
ui_Container1= NULL;
ui_greyTempLabel= NULL;
ui_greyStatusLabel= NULL;
ui_greyLeakLabel= NULL;
ui_greyFreezeLabel= NULL;
ui_Container2= NULL;
ui_Label3= NULL;
ui_Label5= NULL;
ui_Label6= NULL;
ui_Label7= NULL;
ui_freshFaultCont1= NULL;
ui_Label8= NULL;
ui_freshFaultCodeButton1= NULL;
ui_greyFaultCodeButtonLabel= NULL;
ui_freshControlPanel1= NULL;
ui_freshDrainButton1= NULL;
ui_freshDrainLabel1= NULL;

}
