// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

lv_obj_t *ui_Grey_Faults = NULL;lv_obj_t *ui_greyFaultPopupOverlay2 = NULL;lv_obj_t *ui_Label24 = NULL;lv_obj_t *ui_freshFaultPopupCard4 = NULL;lv_obj_t *ui_greyFaultCodeLabel2 = NULL;lv_obj_t *ui_Label19 = NULL;lv_obj_t *ui_Container6 = NULL;lv_obj_t *ui_greyFaultDescLabel2 = NULL;lv_obj_t *ui_greyPopuputtons2 = NULL;lv_obj_t *ui_freshFaultPopupCloseButton5 = NULL;lv_obj_t *ui_Label21 = NULL;lv_obj_t *ui_GreyFaultPopupClearButton2 = NULL;lv_obj_t *ui_Label22 = NULL;
// event funtions
void ui_event_freshFaultPopupCloseButton5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Grey, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Grey_screen_init);
}
}

// build funtions

void ui_Grey_Faults_screen_init(void)
{
ui_Grey_Faults = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Grey_Faults, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_greyFaultPopupOverlay2 = lv_obj_create(ui_Grey_Faults);
lv_obj_remove_style_all(ui_greyFaultPopupOverlay2);
lv_obj_set_width( ui_greyFaultPopupOverlay2, 227);
lv_obj_set_height( ui_greyFaultPopupOverlay2, 308);
lv_obj_set_x( ui_greyFaultPopupOverlay2, 1 );
lv_obj_set_y( ui_greyFaultPopupOverlay2, -3 );
lv_obj_set_align( ui_greyFaultPopupOverlay2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_greyFaultPopupOverlay2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_greyFaultPopupOverlay2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_greyFaultPopupOverlay2, lv_color_hex(0xD46B6B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_greyFaultPopupOverlay2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_greyFaultPopupOverlay2);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label24, 0 );
lv_obj_set_y( ui_Label24, -102 );
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"Fault Details");

ui_freshFaultPopupCard4 = lv_obj_create(ui_greyFaultPopupOverlay2);
lv_obj_remove_style_all(ui_freshFaultPopupCard4);
lv_obj_set_width( ui_freshFaultPopupCard4, 200);
lv_obj_set_height( ui_freshFaultPopupCard4, 192);
lv_obj_set_x( ui_freshFaultPopupCard4, -1 );
lv_obj_set_y( ui_freshFaultPopupCard4, 10 );
lv_obj_set_align( ui_freshFaultPopupCard4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_freshFaultPopupCard4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freshFaultPopupCard4, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_greyFaultCodeLabel2 = lv_label_create(ui_freshFaultPopupCard4);
lv_obj_set_width( ui_greyFaultCodeLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_greyFaultCodeLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_greyFaultCodeLabel2, 0 );
lv_obj_set_y( ui_greyFaultCodeLabel2, -86 );
lv_obj_set_align( ui_greyFaultCodeLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_greyFaultCodeLabel2,"0");

ui_Label19 = lv_label_create(ui_freshFaultPopupCard4);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, 0 );
lv_obj_set_y( ui_Label19, -60 );
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"Description:");

ui_Container6 = lv_obj_create(ui_freshFaultPopupCard4);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 170);
lv_obj_set_height( ui_Container6, 122);
lv_obj_set_x( ui_Container6, 0 );
lv_obj_set_y( ui_Container6, 14 );
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_greyFaultDescLabel2 = lv_label_create(ui_Container6);
lv_obj_set_width( ui_greyFaultDescLabel2, lv_pct(100));
lv_obj_set_height( ui_greyFaultDescLabel2, lv_pct(100));
lv_obj_set_align( ui_greyFaultDescLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_greyFaultDescLabel2,"\nNo Active Fault");
lv_obj_set_style_text_align(ui_greyFaultDescLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_greyPopuputtons2 = lv_obj_create(ui_greyFaultPopupOverlay2);
lv_obj_remove_style_all(ui_greyPopuputtons2);
lv_obj_set_width( ui_greyPopuputtons2, 222);
lv_obj_set_height( ui_greyPopuputtons2, 50);
lv_obj_set_x( ui_greyPopuputtons2, 0 );
lv_obj_set_y( ui_greyPopuputtons2, 125 );
lv_obj_set_align( ui_greyPopuputtons2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_greyPopuputtons2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_greyPopuputtons2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_greyPopuputtons2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_freshFaultPopupCloseButton5 = lv_button_create(ui_greyPopuputtons2);
lv_obj_set_width( ui_freshFaultPopupCloseButton5, 100);
lv_obj_set_height( ui_freshFaultPopupCloseButton5, 40);
lv_obj_set_x( ui_freshFaultPopupCloseButton5, 0 );
lv_obj_set_y( ui_freshFaultPopupCloseButton5, 116 );
lv_obj_set_align( ui_freshFaultPopupCloseButton5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_freshFaultPopupCloseButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_freshFaultPopupCloseButton5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label21 = lv_label_create(ui_freshFaultPopupCloseButton5);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"Back");

ui_GreyFaultPopupClearButton2 = lv_button_create(ui_greyPopuputtons2);
lv_obj_set_width( ui_GreyFaultPopupClearButton2, 100);
lv_obj_set_height( ui_GreyFaultPopupClearButton2, 40);
lv_obj_set_x( ui_GreyFaultPopupClearButton2, 0 );
lv_obj_set_y( ui_GreyFaultPopupClearButton2, 116 );
lv_obj_set_align( ui_GreyFaultPopupClearButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_GreyFaultPopupClearButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_GreyFaultPopupClearButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label22 = lv_label_create(ui_GreyFaultPopupClearButton2);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"Clear");

lv_obj_add_event_cb(ui_freshFaultPopupCloseButton5, ui_event_freshFaultPopupCloseButton5, LV_EVENT_ALL, NULL);

}

void ui_Grey_Faults_screen_destroy(void)
{
   if (ui_Grey_Faults) lv_obj_del(ui_Grey_Faults);

// NULL screen variables
ui_Grey_Faults= NULL;
ui_greyFaultPopupOverlay2= NULL;
ui_Label24= NULL;
ui_freshFaultPopupCard4= NULL;
ui_greyFaultCodeLabel2= NULL;
ui_Label19= NULL;
ui_Container6= NULL;
ui_greyFaultDescLabel2= NULL;
ui_greyPopuputtons2= NULL;
ui_freshFaultPopupCloseButton5= NULL;
ui_Label21= NULL;
ui_GreyFaultPopupClearButton2= NULL;
ui_Label22= NULL;

}
