// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_GREY_FAULTS_H
#define UI_GREY_FAULTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Grey_Faults
extern void ui_Grey_Faults_screen_init(void);
extern void ui_Grey_Faults_screen_destroy(void);
extern lv_obj_t *ui_Grey_Faults;
extern lv_obj_t *ui_greyFaultPopupOverlay2;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_freshFaultPopupCard4;
extern lv_obj_t *ui_greyFaultCodeLabel2;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_greyFaultDescLabel2;
extern lv_obj_t *ui_greyPopuputtons2;
extern void ui_event_freshFaultPopupCloseButton5( lv_event_t * e);
extern lv_obj_t *ui_freshFaultPopupCloseButton5;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_GreyFaultPopupClearButton2;
extern lv_obj_t *ui_Label22;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

