// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_GREY_H
#define UI_GREY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Grey
extern void ui_Grey_screen_init(void);
extern void ui_Grey_screen_destroy(void);
extern lv_obj_t *ui_Grey;
extern lv_obj_t *ui_freshroot1;
extern lv_obj_t *ui_hometitelpanel2;
extern void ui_event_ImgButton2( lv_event_t * e);
extern lv_obj_t *ui_ImgButton2;
extern lv_obj_t *ui_freshMainCard1;
extern lv_obj_t *ui_greyLevelBar;
extern lv_obj_t *ui_greyLevelLabel;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_greyTempLabel;
extern lv_obj_t *ui_greyStatusLabel;
extern lv_obj_t *ui_greyLeakLabel;
extern lv_obj_t *ui_greyFreezeLabel;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_freshFaultCont1;
extern lv_obj_t *ui_Label8;
extern void ui_event_freshFaultCodeButton1( lv_event_t * e);
extern lv_obj_t *ui_freshFaultCodeButton1;
extern lv_obj_t *ui_greyFaultCodeButtonLabel;
extern lv_obj_t *ui_freshControlPanel1;
extern lv_obj_t *ui_freshDrainButton1;
extern lv_obj_t *ui_freshDrainLabel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

