// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern lv_obj_t *ui_home;
extern lv_obj_t *ui_homeroot;
extern lv_obj_t *ui_homeheader;
extern lv_obj_t *ui_Label42;
extern lv_obj_t *ui_homeCydsettingsButton;
extern lv_obj_t *ui_homeheaderWifiConnected;
extern lv_obj_t *ui_homeFreshCard;
extern lv_obj_t *ui_homeFreshLevelArc;
extern lv_obj_t *ui_homeFreshLevelLabel;
extern lv_obj_t *ui_homefreshcont;
extern lv_obj_t *ui_homeFreshTitleLabel;
extern lv_obj_t *ui_homeFreshStatusLabel;
extern lv_obj_t *ui_homeFreshTempLabel;
extern lv_obj_t *ui_homeWasteCard;
extern lv_obj_t *ui_homegreycont;
extern lv_obj_t *ui_homeGreyTitleLabel;
extern lv_obj_t *ui_homeGreyStatusLabel;
extern lv_obj_t *ui_homeGreyTempLabel;
extern lv_obj_t *ui_homeGreyLevelArc;
extern lv_obj_t *ui_homeGreyLevelLabel;
extern lv_obj_t *ui_homeFreshButton;
extern lv_obj_t *ui_homeWasteButton;
extern lv_obj_t *ui_homeFreshSetupButton;
extern lv_obj_t *ui_Label62;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_homeWasteSetupButton;
extern lv_obj_t *ui_Label80;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_hootOverlayAssignRole;
extern lv_obj_t *ui_contasignheader2;
extern lv_obj_t *ui_lblasign2;
extern lv_obj_t *ui_contasigndevice2;
extern lv_obj_t *ui_Label97;
extern lv_obj_t *ui_homeAssignDeviceList;
extern lv_obj_t *ui_contasignbuttons2;
extern lv_obj_t *ui_homeAssignFreshButton;
extern lv_obj_t *ui_Label98;
extern lv_obj_t *ui_homeAssignWasteButton;
extern lv_obj_t *ui_Label99;
extern lv_obj_t *ui_contasignbuttons3;
extern lv_obj_t *ui_homeAssignCancelButton;
extern lv_obj_t *ui_Label100;
extern lv_obj_t *ui_homeAssignConfirmButton;
extern lv_obj_t *ui_Label101;
// CUSTOM VARIABLES
extern lv_obj_t *uic_home;
extern lv_obj_t *uic_homeGreyTitleLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

