// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern lv_obj_t *ui_home;
extern lv_obj_t *ui_homeroot;
extern lv_obj_t *ui_titlepanel1;
extern void ui_event_titlepanel1_ImgButton1( lv_event_t * e);
extern void ui_event_homeFreshCard( lv_event_t * e);
extern lv_obj_t *ui_homeFreshCard;
extern lv_obj_t *ui_homeFreshLevelArc;
extern lv_obj_t *ui_homeFreshLevelLabel;
extern lv_obj_t *ui_homefreshcont;
extern lv_obj_t *ui_homeFreshTitleLabel;
extern lv_obj_t *ui_homeFreshStatusLabel;
extern lv_obj_t *ui_homeFreshTempLabel;
extern void ui_event_homeGreyCard( lv_event_t * e);
extern lv_obj_t *ui_homeGreyCard;
extern lv_obj_t *ui_homegreycont;
extern lv_obj_t *ui_homeGreyTitleLabel;
extern lv_obj_t *ui_homeGreyStatusLabel;
extern lv_obj_t *ui_homeGreyTempLabel;
extern lv_obj_t *ui_homeGreyLevelArc;
extern lv_obj_t *ui_homeGreyLevelLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_home;
extern lv_obj_t *uic_homeGreyTitleLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

