// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_black[1] = {0x3D3B3B};
const ui_theme_variable_t _ui_theme_alpha_black[1] = {255};

const ui_theme_variable_t _ui_theme_color_text[1] = {0xFDF9F9};
const ui_theme_variable_t _ui_theme_alpha_text[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

