// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_WIFISETTINGS_H
#define UI_WIFISETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifisettings
extern void ui_wifisettings_screen_init(void);
extern void ui_wifisettings_screen_destroy(void);
extern lv_obj_t *ui_wifisettings;
extern lv_obj_t *ui_wifisetroot;
extern lv_obj_t *ui_contwifisetheader;
extern void ui_event_ImgButton6( lv_event_t * e);
extern lv_obj_t *ui_ImgButton6;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_contwifisetstatus;
extern lv_obj_t *ui_lblWifiSsid;
extern lv_obj_t *ui_lblWifiIP;
extern lv_obj_t *ui_contwifipaired;
extern lv_obj_t *ui_lblWifipairedcontrollers;
extern lv_obj_t *ui_lblWifipairedcontrollers1;
extern lv_obj_t *ui_lblWifipairedcontrollers2;
extern lv_obj_t *ui_contwifidevlist;
extern lv_obj_t *ui_lblwifidevempty;
extern lv_obj_t *ui_wifidevicetemplate;
extern lv_obj_t *ui_lblwifidevnametemplate;
extern lv_obj_t *ui_lblwifideviptemplate;
extern lv_obj_t *ui_wifidevicetemplate1;
extern lv_obj_t *ui_lblwifidevnametemplate1;
extern lv_obj_t *ui_lblwifideviptemplate1;
extern lv_obj_t *ui_wifirootscanbtn;
extern lv_obj_t *ui_Label37;
extern lv_obj_t *ui_overlayAssignWifiRole;
extern lv_obj_t *ui_contasign5;
extern lv_obj_t *ui_lblasign2;
extern lv_obj_t *ui_contasign3;
extern lv_obj_t *ui_lvlassigndevicetitle2;
extern lv_obj_t *ui_WifiAssignDeviceName;
extern lv_obj_t *ui_contasignbuttons4;
extern lv_obj_t *ui_buttonbootasignfresh4;
extern lv_obj_t *ui_Label41;
extern lv_obj_t *ui_buttonbootasignwaste4;
extern lv_obj_t *ui_Label36;
extern lv_obj_t *ui_contasignbuttons2;
extern lv_obj_t *ui_buttonbootasignfresh2;
extern lv_obj_t *ui_Label38;
extern lv_obj_t *ui_buttonbootasignwaste2;
extern lv_obj_t *ui_Label39;
// CUSTOM VARIABLES
extern lv_obj_t *uic_WifiAssignDeviceName;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

