// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_WASTE_H
#define UI_WASTE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_waste
extern void ui_waste_screen_init(void);
extern void ui_waste_screen_destroy(void);
extern lv_obj_t *ui_waste;
extern lv_obj_t *ui_freshroot1;
extern lv_obj_t *ui_wasteheader;
extern lv_obj_t *ui_wasteheaderlabel;
extern lv_obj_t *ui_wasteSettingsButton;
extern lv_obj_t *ui_wasteBackButton;
extern lv_obj_t *ui_Label44;
extern lv_obj_t *ui_wastemaincard;
extern lv_obj_t *ui_wasteLevelBar;
extern lv_obj_t *ui_wasteLevelLabel;
extern lv_obj_t *ui_wastecont2;
extern lv_obj_t *ui_wasteTempLabel;
extern lv_obj_t *ui_wasteStatusLabel;
extern lv_obj_t *ui_wasteLeakLabel;
extern lv_obj_t *ui_wasteFreezeLabel;
extern lv_obj_t *ui_wastelabels;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_wastefaultcont;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_wasteFaultButton;
extern lv_obj_t *ui_wasteFaultButtonLabel;
extern lv_obj_t *ui_wastecontrolpanel;
extern lv_obj_t *ui_WasteDrainButton;
extern lv_obj_t *ui_wastedrainlabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

