// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_WASTESETTINGS_H
#define UI_WASTESETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wastesettings
extern void ui_wastesettings_screen_init(void);
extern void ui_wastesettings_screen_destroy(void);
extern lv_obj_t *ui_wastesettings;
extern lv_obj_t *ui_wastesettingsroot;
extern lv_obj_t *ui_wastesettingsheader;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_wastesettingsBackButton;
extern lv_obj_t *ui_Label45;
extern lv_obj_t *ui_wastesettingsMainCard;
extern lv_obj_t *ui_wastesettingslabels;
extern lv_obj_t *ui_Label73;
extern lv_obj_t *ui_Label64;
extern lv_obj_t *ui_Label66;
extern lv_obj_t *ui_Label67;
extern lv_obj_t *ui_Label68;
extern lv_obj_t *ui_Label69;
extern lv_obj_t *ui_Label70;
extern lv_obj_t *ui_Label71;
extern lv_obj_t *ui_wastesettingsControls;
extern lv_obj_t *ui_wastesettingsDrainLevelButton;
extern lv_obj_t *ui_wastesettingsDrainStopLevelLabel;
extern lv_obj_t *ui_wastesettingsSetFullButton;
extern lv_obj_t *ui_wastesettingsFullVoltage;
extern lv_obj_t *ui_wastesettingsSetEmptyButton;
extern lv_obj_t *ui_wastesettingsEmptyVoltage;
extern lv_obj_t *ui_wastesettingsFreezeProtection;
extern lv_obj_t *ui_wastesettingsRestart;
extern lv_obj_t *ui_wastesettingsSafetyOveride;
extern lv_obj_t *ui_wastesettingsValveOveride;
extern lv_obj_t *ui_wastesettingsDiagnostic;
extern lv_obj_t *ui_wastesettingsDrainOverlay;
extern lv_obj_t *ui_wastesettingsOverlayDrainSlider;
extern lv_obj_t *ui_wastesettingsOverlayDrainPercentage;
extern lv_obj_t *ui_wastesettingsOverlayBackButton;
extern lv_obj_t *ui_Label65;
extern lv_obj_t *ui_wastesettingsDiagnosticOverlay;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Label83;
extern lv_obj_t *ui_Label72;
extern lv_obj_t *ui_Label74;
extern lv_obj_t *ui_Label75;
extern lv_obj_t *ui_Label76;
extern lv_obj_t *ui_Label77;
extern lv_obj_t *ui_Label78;
extern lv_obj_t *ui_Label79;
extern lv_obj_t *ui_Label80;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_wastesettingsdiagoverlayIP;
extern lv_obj_t *ui_wastesettingsdiagoverlayID;
extern lv_obj_t *ui_wastesettingsdiagoverlayMAC;
extern lv_obj_t *ui_wastesettingsdiagoverlayStatus;
extern lv_obj_t *ui_wastesettingsdiagoverlayRole;
extern lv_obj_t *ui_wastesettingsdiagoverlayUptime;
extern lv_obj_t *ui_wastesettingsdiagoverlaySignal;
extern lv_obj_t *ui_wastesettingsdiagoverlayVersion;
extern lv_obj_t *ui_wastesettingDiagnosticOverlayBackButton;
extern lv_obj_t *ui_Label81;
// CUSTOM VARIABLES
extern lv_obj_t *uic_wastesettingsFreezeProtection;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

