// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

lv_obj_t *ui_wastefaults = NULL;lv_obj_t *ui_greyFaultPopupOverlay2 = NULL;lv_obj_t *ui_Label24 = NULL;lv_obj_t *ui_wastefaultscard = NULL;lv_obj_t *ui_wastefaultsCodeLabel = NULL;lv_obj_t *ui_Label19 = NULL;lv_obj_t *ui_wastefaultsdescription = NULL;lv_obj_t *ui_wastefaultsCodeDescription = NULL;lv_obj_t *ui_greyPopuputtons2 = NULL;lv_obj_t *ui_wastefaultsBackButton = NULL;lv_obj_t *ui_Label21 = NULL;lv_obj_t *ui_wastefaultsClearButton = NULL;lv_obj_t *ui_Label22 = NULL;
// event funtions

// build funtions

void ui_wastefaults_screen_init(void)
{
ui_wastefaults = lv_obj_create(NULL);
lv_obj_remove_flag( ui_wastefaults, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_wastefaults, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_wastefaults, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_black);

ui_greyFaultPopupOverlay2 = lv_obj_create(ui_wastefaults);
lv_obj_remove_style_all(ui_greyFaultPopupOverlay2);
lv_obj_set_width( ui_greyFaultPopupOverlay2, 227);
lv_obj_set_height( ui_greyFaultPopupOverlay2, 308);
lv_obj_set_x( ui_greyFaultPopupOverlay2, 1 );
lv_obj_set_y( ui_greyFaultPopupOverlay2, -3 );
lv_obj_set_align( ui_greyFaultPopupOverlay2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_greyFaultPopupOverlay2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_greyFaultPopupOverlay2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_greyFaultPopupOverlay2, lv_color_hex(0xD46B6B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_greyFaultPopupOverlay2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_greyFaultPopupOverlay2);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label24, 0 );
lv_obj_set_y( ui_Label24, -102 );
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"Fault Details");

ui_wastefaultscard = lv_obj_create(ui_greyFaultPopupOverlay2);
lv_obj_remove_style_all(ui_wastefaultscard);
lv_obj_set_width( ui_wastefaultscard, 200);
lv_obj_set_height( ui_wastefaultscard, 192);
lv_obj_set_x( ui_wastefaultscard, -1 );
lv_obj_set_y( ui_wastefaultscard, 10 );
lv_obj_set_align( ui_wastefaultscard, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_wastefaultscard, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wastefaultscard, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wastefaultsCodeLabel = lv_label_create(ui_wastefaultscard);
lv_obj_set_width( ui_wastefaultsCodeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wastefaultsCodeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wastefaultsCodeLabel, 0 );
lv_obj_set_y( ui_wastefaultsCodeLabel, -86 );
lv_obj_set_align( ui_wastefaultsCodeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wastefaultsCodeLabel,"test");

ui_Label19 = lv_label_create(ui_wastefaultscard);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, 0 );
lv_obj_set_y( ui_Label19, -60 );
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"Description:");

ui_wastefaultsdescription = lv_obj_create(ui_wastefaultscard);
lv_obj_remove_style_all(ui_wastefaultsdescription);
lv_obj_set_width( ui_wastefaultsdescription, 170);
lv_obj_set_height( ui_wastefaultsdescription, 122);
lv_obj_set_x( ui_wastefaultsdescription, 0 );
lv_obj_set_y( ui_wastefaultsdescription, 14 );
lv_obj_set_align( ui_wastefaultsdescription, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_wastefaultsdescription, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wastefaultsCodeDescription = lv_label_create(ui_wastefaultsdescription);
lv_obj_set_width( ui_wastefaultsCodeDescription, lv_pct(100));
lv_obj_set_height( ui_wastefaultsCodeDescription, lv_pct(100));
lv_obj_set_align( ui_wastefaultsCodeDescription, LV_ALIGN_CENTER );
lv_label_set_text(ui_wastefaultsCodeDescription,"\nNo Active Fault");
lv_obj_set_style_text_align(ui_wastefaultsCodeDescription, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_greyPopuputtons2 = lv_obj_create(ui_greyFaultPopupOverlay2);
lv_obj_remove_style_all(ui_greyPopuputtons2);
lv_obj_set_width( ui_greyPopuputtons2, 222);
lv_obj_set_height( ui_greyPopuputtons2, 50);
lv_obj_set_x( ui_greyPopuputtons2, 0 );
lv_obj_set_y( ui_greyPopuputtons2, 125 );
lv_obj_set_align( ui_greyPopuputtons2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_greyPopuputtons2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_greyPopuputtons2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_greyPopuputtons2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wastefaultsBackButton = lv_button_create(ui_greyPopuputtons2);
lv_obj_set_width( ui_wastefaultsBackButton, 100);
lv_obj_set_height( ui_wastefaultsBackButton, 40);
lv_obj_set_x( ui_wastefaultsBackButton, 0 );
lv_obj_set_y( ui_wastefaultsBackButton, 116 );
lv_obj_set_align( ui_wastefaultsBackButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wastefaultsBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_wastefaultsBackButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label21 = lv_label_create(ui_wastefaultsBackButton);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"Back");

ui_wastefaultsClearButton = lv_button_create(ui_greyPopuputtons2);
lv_obj_set_width( ui_wastefaultsClearButton, 100);
lv_obj_set_height( ui_wastefaultsClearButton, 40);
lv_obj_set_x( ui_wastefaultsClearButton, 0 );
lv_obj_set_y( ui_wastefaultsClearButton, 116 );
lv_obj_set_align( ui_wastefaultsClearButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wastefaultsClearButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_wastefaultsClearButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label22 = lv_label_create(ui_wastefaultsClearButton);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"Clear");

}

void ui_wastefaults_screen_destroy(void)
{
   if (ui_wastefaults) lv_obj_del(ui_wastefaults);

// NULL screen variables
ui_wastefaults= NULL;
ui_greyFaultPopupOverlay2= NULL;
ui_Label24= NULL;
ui_wastefaultscard= NULL;
ui_wastefaultsCodeLabel= NULL;
ui_Label19= NULL;
ui_wastefaultsdescription= NULL;
ui_wastefaultsCodeDescription= NULL;
ui_greyPopuputtons2= NULL;
ui_wastefaultsBackButton= NULL;
ui_Label21= NULL;
ui_wastefaultsClearButton= NULL;
ui_Label22= NULL;

}
