// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

lv_obj_t *ui_waste = NULL;lv_obj_t *ui_freshroot1 = NULL;lv_obj_t *ui_wasteheader = NULL;lv_obj_t *ui_wasteheaderlabel = NULL;lv_obj_t *ui_wasteSettingsButton = NULL;lv_obj_t *ui_wasteBackButton = NULL;lv_obj_t *ui_Label44 = NULL;lv_obj_t *ui_wastemaincard = NULL;lv_obj_t *ui_wasteLevelBar = NULL;lv_obj_t *ui_wasteLevelLabel = NULL;lv_obj_t *ui_wastecont2 = NULL;lv_obj_t *ui_wasteTempLabel = NULL;lv_obj_t *ui_wasteStatusLabel = NULL;lv_obj_t *ui_wasteLeakLabel = NULL;lv_obj_t *ui_wasteFreezeLabel = NULL;lv_obj_t *ui_wastelabels = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_wastefaultcont = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_wasteFaultButton = NULL;lv_obj_t *ui_wasteFaultButtonLabel = NULL;lv_obj_t *ui_wastecontrolpanel = NULL;lv_obj_t *ui_WasteDrainButton = NULL;lv_obj_t *ui_wastedrainlabel = NULL;
// event funtions

// build funtions

void ui_waste_screen_init(void)
{
ui_waste = lv_obj_create(NULL);
lv_obj_remove_flag( ui_waste, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_waste, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_waste, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_black);

ui_freshroot1 = lv_obj_create(ui_waste);
lv_obj_remove_style_all(ui_freshroot1);
lv_obj_set_width( ui_freshroot1, 240);
lv_obj_set_height( ui_freshroot1, 320);
lv_obj_set_align( ui_freshroot1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_freshroot1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_freshroot1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_freshroot1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_freshroot1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_freshroot1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wasteheader = lv_obj_create(ui_freshroot1);
lv_obj_set_height( ui_wasteheader, 50);
lv_obj_set_width( ui_wasteheader, lv_pct(100));
lv_obj_set_x( ui_wasteheader, -16 );
lv_obj_set_y( ui_wasteheader, 4 );
lv_obj_set_align( ui_wasteheader, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_wasteheader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wasteheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wasteheader, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wasteheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wasteheaderlabel = lv_label_create(ui_wasteheader);
lv_obj_set_width( ui_wasteheaderlabel, lv_pct(50));
lv_obj_set_height( ui_wasteheaderlabel, lv_pct(100));
lv_obj_set_x( ui_wasteheaderlabel, 11 );
lv_obj_set_y( ui_wasteheaderlabel, -3 );
lv_obj_set_align( ui_wasteheaderlabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_wasteheaderlabel,"Waste\n");
ui_object_set_themeable_style_property(ui_wasteheaderlabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_wasteheaderlabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_black);
lv_obj_set_style_text_font(ui_wasteheaderlabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wasteSettingsButton = lv_image_create(ui_wasteheader);
lv_image_set_src(ui_wasteSettingsButton, &ui_img_314706763);
lv_obj_set_width( ui_wasteSettingsButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wasteSettingsButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wasteSettingsButton, 84 );
lv_obj_set_y( ui_wasteSettingsButton, 0 );
lv_obj_set_align( ui_wasteSettingsButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wasteSettingsButton, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_wasteSettingsButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wasteBackButton = lv_button_create(ui_wasteheader);
lv_obj_set_width( ui_wasteBackButton, 40);
lv_obj_set_height( ui_wasteBackButton, 40);
lv_obj_set_x( ui_wasteBackButton, -93 );
lv_obj_set_y( ui_wasteBackButton, 0 );
lv_obj_set_align( ui_wasteBackButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wasteBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_wasteBackButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wasteBackButton, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wasteBackButton, lv_color_hex(0x0099A5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wasteBackButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_wasteBackButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_wasteBackButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_wasteBackButton, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_wasteBackButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label44 = lv_label_create(ui_wasteBackButton);
lv_obj_set_width( ui_Label44, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label44, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label44, -2 );
lv_obj_set_y( ui_Label44, 1 );
lv_obj_set_align( ui_Label44, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label44,"<");
lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wastemaincard = lv_obj_create(ui_freshroot1);
lv_obj_set_width( ui_wastemaincard, 224);
lv_obj_set_height( ui_wastemaincard, 180);
lv_obj_set_align( ui_wastemaincard, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_wastemaincard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wastemaincard, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wastemaincard, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wastemaincard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wasteLevelBar = lv_bar_create(ui_wastemaincard);
lv_bar_set_value(ui_wasteLevelBar,75,LV_ANIM_OFF);
lv_bar_set_start_value(ui_wasteLevelBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_wasteLevelBar, 120);
lv_obj_set_height( ui_wasteLevelBar, 50);
lv_obj_set_x( ui_wasteLevelBar, 106 );
lv_obj_set_y( ui_wasteLevelBar, 69 );
lv_obj_set_align( ui_wasteLevelBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_wasteLevelBar, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_rotation(ui_wasteLevelBar, 2700, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_wasteLevelBar, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_wasteLevelBar,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_wasteLevelBar, lv_obj_get_style_pad_right(ui_wasteLevelBar,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_wasteLevelLabel = lv_label_create(ui_wastemaincard);
lv_obj_set_width( ui_wasteLevelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wasteLevelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wasteLevelLabel, 71 );
lv_obj_set_y( ui_wasteLevelLabel, 63 );
lv_obj_set_align( ui_wasteLevelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wasteLevelLabel,"test");

ui_wastecont2 = lv_obj_create(ui_wastemaincard);
lv_obj_remove_style_all(ui_wastecont2);
lv_obj_set_width( ui_wastecont2, 60);
lv_obj_set_height( ui_wastecont2, 120);
lv_obj_set_x( ui_wastecont2, 0 );
lv_obj_set_y( ui_wastecont2, -15 );
lv_obj_set_align( ui_wastecont2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wastecont2,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_wastecont2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wastecont2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wasteTempLabel = lv_label_create(ui_wastecont2);
lv_obj_set_width( ui_wasteTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wasteTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wasteTempLabel, 4 );
lv_obj_set_y( ui_wasteTempLabel, -61 );
lv_obj_set_align( ui_wasteTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wasteTempLabel,"test");

ui_wasteStatusLabel = lv_label_create(ui_wastecont2);
lv_obj_set_width( ui_wasteStatusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wasteStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wasteStatusLabel, 4 );
lv_obj_set_y( ui_wasteStatusLabel, -24 );
lv_obj_set_align( ui_wasteStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wasteStatusLabel,"test");

ui_wasteLeakLabel = lv_label_create(ui_wastecont2);
lv_obj_set_width( ui_wasteLeakLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wasteLeakLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wasteLeakLabel, 4 );
lv_obj_set_y( ui_wasteLeakLabel, -61 );
lv_obj_set_align( ui_wasteLeakLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wasteLeakLabel,"test");

ui_wasteFreezeLabel = lv_label_create(ui_wastecont2);
lv_obj_set_width( ui_wasteFreezeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wasteFreezeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wasteFreezeLabel, 4 );
lv_obj_set_y( ui_wasteFreezeLabel, -61 );
lv_obj_set_align( ui_wasteFreezeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wasteFreezeLabel,"test");

ui_wastelabels = lv_obj_create(ui_wastemaincard);
lv_obj_remove_style_all(ui_wastelabels);
lv_obj_set_width( ui_wastelabels, 60);
lv_obj_set_height( ui_wastelabels, 120);
lv_obj_set_x( ui_wastelabels, -70 );
lv_obj_set_y( ui_wastelabels, -15 );
lv_obj_set_align( ui_wastelabels, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wastelabels,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_wastelabels, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wastelabels, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_wastelabels);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -65 );
lv_obj_set_y( ui_Label3, -61 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Temp");

ui_Label5 = lv_label_create(ui_wastelabels);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -63 );
lv_obj_set_y( ui_Label5, -25 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Status");

ui_Label6 = lv_label_create(ui_wastelabels);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -65 );
lv_obj_set_y( ui_Label6, -61 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Leak");

ui_Label7 = lv_label_create(ui_wastelabels);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -65 );
lv_obj_set_y( ui_Label7, -61 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Freeze");

ui_wastefaultcont = lv_obj_create(ui_wastemaincard);
lv_obj_remove_style_all(ui_wastefaultcont);
lv_obj_set_width( ui_wastefaultcont, 168);
lv_obj_set_height( ui_wastefaultcont, 36);
lv_obj_set_x( ui_wastefaultcont, -33 );
lv_obj_set_y( ui_wastefaultcont, 57 );
lv_obj_set_align( ui_wastefaultcont, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wastefaultcont,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wastefaultcont, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wastefaultcont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_wastefaultcont);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Fault");

ui_wasteFaultButton = lv_button_create(ui_wastefaultcont);
lv_obj_set_width( ui_wasteFaultButton, 50);
lv_obj_set_height( ui_wasteFaultButton, 30);
lv_obj_set_x( ui_wasteFaultButton, 0 );
lv_obj_set_y( ui_wasteFaultButton, 11 );
lv_obj_set_align( ui_wasteFaultButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wasteFaultButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_wasteFaultButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wasteFaultButtonLabel = lv_label_create(ui_wasteFaultButton);
lv_obj_set_width( ui_wasteFaultButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wasteFaultButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wasteFaultButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wasteFaultButtonLabel,"test");

ui_wastecontrolpanel = lv_obj_create(ui_freshroot1);
lv_obj_set_width( ui_wastecontrolpanel, 224);
lv_obj_set_height( ui_wastecontrolpanel, 60);
lv_obj_set_align( ui_wastecontrolpanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wastecontrolpanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wastecontrolpanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wastecontrolpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wastecontrolpanel, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wastecontrolpanel, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wastecontrolpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WasteDrainButton = lv_button_create(ui_wastecontrolpanel);
lv_obj_set_width( ui_WasteDrainButton, 207);
lv_obj_set_height( ui_WasteDrainButton, 50);
lv_obj_set_align( ui_WasteDrainButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WasteDrainButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_WasteDrainButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_WasteDrainButton, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wastedrainlabel = lv_label_create(ui_WasteDrainButton);
lv_obj_set_width( ui_wastedrainlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wastedrainlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wastedrainlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wastedrainlabel,"DRAIN");
lv_obj_set_style_text_font(ui_wastedrainlabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_waste_screen_destroy(void)
{
   if (ui_waste) lv_obj_del(ui_waste);

// NULL screen variables
ui_waste= NULL;
ui_freshroot1= NULL;
ui_wasteheader= NULL;
ui_wasteheaderlabel= NULL;
ui_wasteSettingsButton= NULL;
ui_wasteBackButton= NULL;
ui_Label44= NULL;
ui_wastemaincard= NULL;
ui_wasteLevelBar= NULL;
ui_wasteLevelLabel= NULL;
ui_wastecont2= NULL;
ui_wasteTempLabel= NULL;
ui_wasteStatusLabel= NULL;
ui_wasteLeakLabel= NULL;
ui_wasteFreezeLabel= NULL;
ui_wastelabels= NULL;
ui_Label3= NULL;
ui_Label5= NULL;
ui_Label6= NULL;
ui_Label7= NULL;
ui_wastefaultcont= NULL;
ui_Label8= NULL;
ui_wasteFaultButton= NULL;
ui_wasteFaultButtonLabel= NULL;
ui_wastecontrolpanel= NULL;
ui_WasteDrainButton= NULL;
ui_wastedrainlabel= NULL;

}
