// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

lv_obj_t *uic_WifiAssignDeviceName;
lv_obj_t *ui_wifisettings = NULL;lv_obj_t *ui_wifisetroot = NULL;lv_obj_t *ui_contwifisetheader = NULL;lv_obj_t *ui_ImgButton6 = NULL;lv_obj_t *ui_Label34 = NULL;lv_obj_t *ui_contwifisetstatus = NULL;lv_obj_t *ui_lblWifiSsid = NULL;lv_obj_t *ui_lblWifiIP = NULL;lv_obj_t *ui_contwifipaired = NULL;lv_obj_t *ui_lblWifipairedcontrollers = NULL;lv_obj_t *ui_lblWifipairedcontrollers1 = NULL;lv_obj_t *ui_lblWifipairedcontrollers2 = NULL;lv_obj_t *ui_contwifidevlist = NULL;lv_obj_t *ui_lblwifidevempty = NULL;lv_obj_t *ui_wifidevicetemplate = NULL;lv_obj_t *ui_lblwifidevnametemplate = NULL;lv_obj_t *ui_lblwifideviptemplate = NULL;lv_obj_t *ui_wifidevicetemplate1 = NULL;lv_obj_t *ui_lblwifidevnametemplate1 = NULL;lv_obj_t *ui_lblwifideviptemplate1 = NULL;lv_obj_t *ui_wifirootscanbtn = NULL;lv_obj_t *ui_Label37 = NULL;lv_obj_t *ui_overlayAssignWifiRole = NULL;lv_obj_t *ui_contasign5 = NULL;lv_obj_t *ui_lblasign2 = NULL;lv_obj_t *ui_contasign3 = NULL;lv_obj_t *ui_lvlassigndevicetitle2 = NULL;lv_obj_t *ui_WifiAssignDeviceName = NULL;lv_obj_t *ui_contasignbuttons4 = NULL;lv_obj_t *ui_buttonbootasignfresh4 = NULL;lv_obj_t *ui_Label41 = NULL;lv_obj_t *ui_buttonbootasignwaste4 = NULL;lv_obj_t *ui_Label36 = NULL;lv_obj_t *ui_contasignbuttons2 = NULL;lv_obj_t *ui_buttonbootasignfresh2 = NULL;lv_obj_t *ui_Label38 = NULL;lv_obj_t *ui_buttonbootasignwaste2 = NULL;lv_obj_t *ui_Label39 = NULL;
// event funtions
void ui_event_ImgButton6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home_screen_init);
}
}

// build funtions

void ui_wifisettings_screen_init(void)
{
ui_wifisettings = lv_obj_create(NULL);
lv_obj_remove_flag( ui_wifisettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_wifisettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_wifisettings, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_black);
lv_obj_set_style_bg_grad_color(ui_wifisettings, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_wifisetroot = lv_obj_create(ui_wifisettings);
lv_obj_remove_style_all(ui_wifisetroot);
lv_obj_set_width( ui_wifisetroot, 240);
lv_obj_set_height( ui_wifisetroot, 320);
lv_obj_set_align( ui_wifisetroot, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wifisetroot,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_wifisetroot, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wifisetroot, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_wifisetroot, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_wifisetroot, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_contwifisetheader = lv_obj_create(ui_wifisetroot);
lv_obj_set_height( ui_contwifisetheader, 50);
lv_obj_set_width( ui_contwifisetheader, lv_pct(100));
lv_obj_set_x( ui_contwifisetheader, -16 );
lv_obj_set_y( ui_contwifisetheader, 4 );
lv_obj_set_align( ui_contwifisetheader, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_contwifisetheader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_contwifisetheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_contwifisetheader, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_contwifisetheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgButton6 = lv_imagebutton_create(ui_contwifisetheader);
lv_imagebutton_set_src(ui_ImgButton6, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_791807475, NULL);
lv_imagebutton_set_src(ui_ImgButton6, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_791807475, NULL);
lv_obj_set_width( ui_ImgButton6, 60);
lv_obj_set_height( ui_ImgButton6, 59);
lv_obj_set_x( ui_ImgButton6, -90 );
lv_obj_set_y( ui_ImgButton6, -1 );
lv_obj_set_align( ui_ImgButton6, LV_ALIGN_CENTER );

ui_Label34 = lv_label_create(ui_contwifisetheader);
lv_obj_set_width( ui_Label34, lv_pct(50));
lv_obj_set_height( ui_Label34, lv_pct(100));
lv_obj_set_x( ui_Label34, 11 );
lv_obj_set_y( ui_Label34, -3 );
lv_obj_set_align( ui_Label34, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label34," Wi-Fi\n");
ui_object_set_themeable_style_property(ui_Label34, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_Label34, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_black);
lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_contwifisetstatus = lv_obj_create(ui_wifisetroot);
lv_obj_remove_style_all(ui_contwifisetstatus);
lv_obj_set_width( ui_contwifisetstatus, 220);
lv_obj_set_height( ui_contwifisetstatus, 41);
lv_obj_set_align( ui_contwifisetstatus, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_contwifisetstatus,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_contwifisetstatus, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_contwifisetstatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_contwifisetstatus, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_contwifisetstatus, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblWifiSsid = lv_label_create(ui_contwifisetstatus);
lv_obj_set_width( ui_lblWifiSsid, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblWifiSsid, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblWifiSsid, 2 );
lv_obj_set_y( ui_lblWifiSsid, -16 );
lv_obj_set_align( ui_lblWifiSsid, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblWifiSsid,"SSID: (not connected)");
ui_object_set_themeable_style_property(ui_lblWifiSsid, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lblWifiSsid, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);

ui_lblWifiIP = lv_label_create(ui_contwifisetstatus);
lv_obj_set_width( ui_lblWifiIP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblWifiIP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblWifiIP, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblWifiIP,"IP: 0.0.0.0");
ui_object_set_themeable_style_property(ui_lblWifiIP, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lblWifiIP, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);

ui_contwifipaired = lv_obj_create(ui_wifisetroot);
lv_obj_remove_style_all(ui_contwifipaired);
lv_obj_set_width( ui_contwifipaired, 220);
lv_obj_set_height( ui_contwifipaired, 63);
lv_obj_set_align( ui_contwifipaired, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_contwifipaired,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_contwifipaired, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_contwifipaired, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_contwifipaired, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_contwifipaired, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblWifipairedcontrollers = lv_label_create(ui_contwifipaired);
lv_obj_set_width( ui_lblWifipairedcontrollers, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblWifipairedcontrollers, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblWifipairedcontrollers, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblWifipairedcontrollers,"Paired Controllers");
ui_object_set_themeable_style_property(ui_lblWifipairedcontrollers, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lblWifipairedcontrollers, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_decor(ui_lblWifipairedcontrollers, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblWifipairedcontrollers1 = lv_label_create(ui_contwifipaired);
lv_obj_set_width( ui_lblWifipairedcontrollers1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblWifipairedcontrollers1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblWifipairedcontrollers1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblWifipairedcontrollers1,"Fresh: (none)");
ui_object_set_themeable_style_property(ui_lblWifipairedcontrollers1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lblWifipairedcontrollers1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);

ui_lblWifipairedcontrollers2 = lv_label_create(ui_contwifipaired);
lv_obj_set_width( ui_lblWifipairedcontrollers2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblWifipairedcontrollers2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblWifipairedcontrollers2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblWifipairedcontrollers2,"Waste: (none)");
ui_object_set_themeable_style_property(ui_lblWifipairedcontrollers2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lblWifipairedcontrollers2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);

ui_contwifidevlist = lv_obj_create(ui_wifisetroot);
lv_obj_remove_style_all(ui_contwifidevlist);
lv_obj_set_width( ui_contwifidevlist, 220);
lv_obj_set_height( ui_contwifidevlist, 94);
lv_obj_set_x( ui_contwifidevlist, 2 );
lv_obj_set_y( ui_contwifidevlist, -8 );
lv_obj_set_align( ui_contwifidevlist, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_contwifidevlist,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_contwifidevlist, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_contwifidevlist, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_radius(ui_contwifidevlist, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_contwifidevlist, lv_color_hex(0x908686), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_contwifidevlist, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_contwifidevlist, lv_color_hex(0x228FE5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_contwifidevlist, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_contwifidevlist, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_contwifidevlist, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_contwifidevlist, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblwifidevempty = lv_label_create(ui_contwifidevlist);
lv_obj_set_width( ui_lblwifidevempty, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblwifidevempty, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblwifidevempty, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblwifidevempty,"No Controllers Found");
lv_obj_add_flag( ui_lblwifidevempty, LV_OBJ_FLAG_HIDDEN );   /// Flags
ui_object_set_themeable_style_property(ui_lblwifidevempty, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lblwifidevempty, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);

ui_wifidevicetemplate = lv_obj_create(ui_contwifidevlist);
lv_obj_remove_style_all(ui_wifidevicetemplate);
lv_obj_set_width( ui_wifidevicetemplate, 200);
lv_obj_set_height( ui_wifidevicetemplate, 40);
lv_obj_set_x( ui_wifidevicetemplate, 0 );
lv_obj_set_y( ui_wifidevicetemplate, -1 );
lv_obj_set_align( ui_wifidevicetemplate, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wifidevicetemplate,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wifidevicetemplate, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wifidevicetemplate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wifidevicetemplate, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wifidevicetemplate, lv_color_hex(0xF4EFEF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifidevicetemplate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_wifidevicetemplate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_wifidevicetemplate, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblwifidevnametemplate = lv_label_create(ui_wifidevicetemplate);
lv_obj_set_width( ui_lblwifidevnametemplate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblwifidevnametemplate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblwifidevnametemplate, 51 );
lv_obj_set_y( ui_lblwifidevnametemplate, 14 );
lv_obj_set_align( ui_lblwifidevnametemplate, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblwifidevnametemplate,"TankPro -XXXX");
lv_obj_set_style_text_font(ui_lblwifidevnametemplate, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblwifideviptemplate = lv_label_create(ui_wifidevicetemplate);
lv_obj_set_width( ui_lblwifideviptemplate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblwifideviptemplate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblwifideviptemplate, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblwifideviptemplate,"IP: 192.168.10.12");
lv_obj_set_style_text_font(ui_lblwifideviptemplate, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifidevicetemplate1 = lv_obj_create(ui_contwifidevlist);
lv_obj_remove_style_all(ui_wifidevicetemplate1);
lv_obj_set_width( ui_wifidevicetemplate1, 200);
lv_obj_set_height( ui_wifidevicetemplate1, 40);
lv_obj_set_x( ui_wifidevicetemplate1, 0 );
lv_obj_set_y( ui_wifidevicetemplate1, -1 );
lv_obj_set_align( ui_wifidevicetemplate1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wifidevicetemplate1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wifidevicetemplate1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_wifidevicetemplate1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wifidevicetemplate1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wifidevicetemplate1, lv_color_hex(0xF4EFEF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifidevicetemplate1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_wifidevicetemplate1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_wifidevicetemplate1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblwifidevnametemplate1 = lv_label_create(ui_wifidevicetemplate1);
lv_obj_set_width( ui_lblwifidevnametemplate1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblwifidevnametemplate1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblwifidevnametemplate1, 51 );
lv_obj_set_y( ui_lblwifidevnametemplate1, 14 );
lv_obj_set_align( ui_lblwifidevnametemplate1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblwifidevnametemplate1,"TankPro -XXXX");
lv_obj_set_style_text_font(ui_lblwifidevnametemplate1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblwifideviptemplate1 = lv_label_create(ui_wifidevicetemplate1);
lv_obj_set_width( ui_lblwifideviptemplate1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblwifideviptemplate1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblwifideviptemplate1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblwifideviptemplate1,"IP: 192.168.10.12");
lv_obj_set_style_text_font(ui_lblwifideviptemplate1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifirootscanbtn = lv_button_create(ui_wifisetroot);
lv_obj_set_width( ui_wifirootscanbtn, 220);
lv_obj_set_height( ui_wifirootscanbtn, 35);
lv_obj_set_align( ui_wifirootscanbtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifirootscanbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_wifirootscanbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label37 = lv_label_create(ui_wifirootscanbtn);
lv_obj_set_width( ui_Label37, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label37, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label37, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label37,"Scan");

ui_overlayAssignWifiRole = lv_obj_create(ui_wifisettings);
lv_obj_remove_style_all(ui_overlayAssignWifiRole);
lv_obj_set_width( ui_overlayAssignWifiRole, 240);
lv_obj_set_height( ui_overlayAssignWifiRole, 318);
lv_obj_set_align( ui_overlayAssignWifiRole, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_overlayAssignWifiRole,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_overlayAssignWifiRole, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_overlayAssignWifiRole, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_overlayAssignWifiRole, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_overlayAssignWifiRole, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_overlayAssignWifiRole, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_black);
lv_obj_set_style_blend_mode(ui_overlayAssignWifiRole, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_overlayAssignWifiRole, 240, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_overlayAssignWifiRole, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_overlayAssignWifiRole, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_contasign5 = lv_obj_create(ui_overlayAssignWifiRole);
lv_obj_remove_style_all(ui_contasign5);
lv_obj_set_width( ui_contasign5, 220);
lv_obj_set_height( ui_contasign5, 43);
lv_obj_set_x( ui_contasign5, 1 );
lv_obj_set_y( ui_contasign5, -53 );
lv_obj_set_align( ui_contasign5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_contasign5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_contasign5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_contasign5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_contasign5, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_contasign5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_contasign5, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblasign2 = lv_label_create(ui_contasign5);
lv_obj_set_width( ui_lblasign2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblasign2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblasign2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblasign2,"Assign Role");
ui_object_set_themeable_style_property(ui_lblasign2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lblasign2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_font(ui_lblasign2, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_contasign3 = lv_obj_create(ui_overlayAssignWifiRole);
lv_obj_remove_style_all(ui_contasign3);
lv_obj_set_width( ui_contasign3, 220);
lv_obj_set_height( ui_contasign3, 100);
lv_obj_set_align( ui_contasign3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_contasign3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_contasign3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_contasign3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_contasign3, 35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_contasign3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lvlassigndevicetitle2 = lv_label_create(ui_contasign3);
lv_obj_set_width( ui_lvlassigndevicetitle2, lv_pct(100));
lv_obj_set_height( ui_lvlassigndevicetitle2, lv_pct(10));
lv_obj_set_x( ui_lvlassigndevicetitle2, -4 );
lv_obj_set_y( ui_lvlassigndevicetitle2, -51 );
lv_obj_set_align( ui_lvlassigndevicetitle2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lvlassigndevicetitle2,"Device:");
ui_object_set_themeable_style_property(ui_lvlassigndevicetitle2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lvlassigndevicetitle2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_align(ui_lvlassigndevicetitle2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiAssignDeviceName = lv_label_create(ui_contasign3);
lv_obj_set_width( ui_WifiAssignDeviceName, lv_pct(100));
lv_obj_set_height( ui_WifiAssignDeviceName, lv_pct(10));
lv_obj_set_x( ui_WifiAssignDeviceName, -4 );
lv_obj_set_y( ui_WifiAssignDeviceName, -51 );
lv_obj_set_align( ui_WifiAssignDeviceName, LV_ALIGN_CENTER );
lv_label_set_text(ui_WifiAssignDeviceName,"None");
ui_object_set_themeable_style_property(ui_WifiAssignDeviceName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_WifiAssignDeviceName, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_align(ui_WifiAssignDeviceName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_contasignbuttons4 = lv_obj_create(ui_overlayAssignWifiRole);
lv_obj_remove_style_all(ui_contasignbuttons4);
lv_obj_set_width( ui_contasignbuttons4, 220);
lv_obj_set_height( ui_contasignbuttons4, 97);
lv_obj_set_align( ui_contasignbuttons4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_contasignbuttons4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_contasignbuttons4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_contasignbuttons4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_contasignbuttons4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_contasignbuttons4, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonbootasignfresh4 = lv_button_create(ui_contasignbuttons4);
lv_obj_set_width( ui_buttonbootasignfresh4, 80);
lv_obj_set_height( ui_buttonbootasignfresh4, 40);
lv_obj_set_align( ui_buttonbootasignfresh4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttonbootasignfresh4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonbootasignfresh4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label41 = lv_label_create(ui_buttonbootasignfresh4);
lv_obj_set_width( ui_Label41, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label41, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label41, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label41,"Fresh");

ui_buttonbootasignwaste4 = lv_button_create(ui_contasignbuttons4);
lv_obj_set_width( ui_buttonbootasignwaste4, 80);
lv_obj_set_height( ui_buttonbootasignwaste4, 40);
lv_obj_set_align( ui_buttonbootasignwaste4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttonbootasignwaste4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonbootasignwaste4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label36 = lv_label_create(ui_buttonbootasignwaste4);
lv_obj_set_width( ui_Label36, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label36, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label36,"Waste");

ui_contasignbuttons2 = lv_obj_create(ui_overlayAssignWifiRole);
lv_obj_remove_style_all(ui_contasignbuttons2);
lv_obj_set_width( ui_contasignbuttons2, 220);
lv_obj_set_height( ui_contasignbuttons2, 47);
lv_obj_set_align( ui_contasignbuttons2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_contasignbuttons2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_contasignbuttons2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_contasignbuttons2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_contasignbuttons2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_contasignbuttons2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonbootasignfresh2 = lv_button_create(ui_contasignbuttons2);
lv_obj_set_width( ui_buttonbootasignfresh2, 80);
lv_obj_set_height( ui_buttonbootasignfresh2, 40);
lv_obj_set_align( ui_buttonbootasignfresh2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttonbootasignfresh2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonbootasignfresh2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label38 = lv_label_create(ui_buttonbootasignfresh2);
lv_obj_set_width( ui_Label38, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label38, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label38, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label38,"Cancel");

ui_buttonbootasignwaste2 = lv_button_create(ui_contasignbuttons2);
lv_obj_set_width( ui_buttonbootasignwaste2, 80);
lv_obj_set_height( ui_buttonbootasignwaste2, 40);
lv_obj_set_align( ui_buttonbootasignwaste2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttonbootasignwaste2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonbootasignwaste2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label39 = lv_label_create(ui_buttonbootasignwaste2);
lv_obj_set_width( ui_Label39, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label39, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label39, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label39,"Confirm");

lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);
uic_WifiAssignDeviceName = ui_WifiAssignDeviceName;

}

void ui_wifisettings_screen_destroy(void)
{
   if (ui_wifisettings) lv_obj_del(ui_wifisettings);

// NULL screen variables
ui_wifisettings= NULL;
ui_wifisetroot= NULL;
ui_contwifisetheader= NULL;
ui_ImgButton6= NULL;
ui_Label34= NULL;
ui_contwifisetstatus= NULL;
ui_lblWifiSsid= NULL;
ui_lblWifiIP= NULL;
ui_contwifipaired= NULL;
ui_lblWifipairedcontrollers= NULL;
ui_lblWifipairedcontrollers1= NULL;
ui_lblWifipairedcontrollers2= NULL;
ui_contwifidevlist= NULL;
ui_lblwifidevempty= NULL;
ui_wifidevicetemplate= NULL;
ui_lblwifidevnametemplate= NULL;
ui_lblwifideviptemplate= NULL;
ui_wifidevicetemplate1= NULL;
ui_lblwifidevnametemplate1= NULL;
ui_lblwifideviptemplate1= NULL;
ui_wifirootscanbtn= NULL;
ui_Label37= NULL;
ui_overlayAssignWifiRole= NULL;
ui_contasign5= NULL;
ui_lblasign2= NULL;
ui_contasign3= NULL;
ui_lvlassigndevicetitle2= NULL;
uic_WifiAssignDeviceName= NULL;
ui_WifiAssignDeviceName= NULL;
ui_contasignbuttons4= NULL;
ui_buttonbootasignfresh4= NULL;
ui_Label41= NULL;
ui_buttonbootasignwaste4= NULL;
ui_Label36= NULL;
ui_contasignbuttons2= NULL;
ui_buttonbootasignfresh2= NULL;
ui_Label38= NULL;
ui_buttonbootasignwaste2= NULL;
ui_Label39= NULL;

}
