// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#include "ui.h"

lv_obj_t *uic_directlabel;
lv_obj_t *uic_bootDirectLabel;
lv_obj_t *uic_bootDirectButton;
lv_obj_t *uic_bootDirectPanel;
lv_obj_t *uic_wifilabel;
lv_obj_t *uic_wifibuttonlabel;
lv_obj_t *uic_bootWifiButton;
lv_obj_t *uic_bootwifipanel;
lv_obj_t *uic_bootTitle3;
lv_obj_t *uic_bootTitle;
lv_obj_t *uic_bootRoot;
lv_obj_t *uic_boot;
lv_obj_t *ui_boot = NULL;lv_obj_t *ui_bootRoot = NULL;lv_obj_t *ui_bootTitle = NULL;lv_obj_t *ui_bootTitle3 = NULL;lv_obj_t *ui_bootwifipanel = NULL;lv_obj_t *ui_bootWifiButton = NULL;lv_obj_t *ui_wifibuttonlabel = NULL;lv_obj_t *ui_wifidesclabel = NULL;lv_obj_t *ui_bootDirectPanel = NULL;lv_obj_t *ui_bootDirectButton = NULL;lv_obj_t *ui_bootDirectLabel = NULL;lv_obj_t *ui_directdesclabel = NULL;lv_obj_t *ui_bootFirmwareLabel = NULL;lv_obj_t *ui_overlayBootWifi = NULL;lv_obj_t *ui_popupbootwifi = NULL;lv_obj_t *ui_lblbootwifititle = NULL;lv_obj_t *ui_lblbootwifidesc = NULL;lv_obj_t *ui_ssid_container = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_bootWifissid = NULL;lv_obj_t *ui_pwd_container1 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_bootWifipass = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Container4 = NULL;lv_obj_t *ui_buttonBootWifiBack = NULL;lv_obj_t *ui_Label11 = NULL;
// event funtions
void ui_event_bootWifiButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      btn_boot_wifi_event( e );
}
}

// build funtions

void ui_boot_screen_init(void)
{
ui_boot = lv_obj_create(NULL);
lv_obj_remove_flag( ui_boot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_boot, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_boot, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_black);

ui_bootRoot = lv_obj_create(ui_boot);
lv_obj_remove_style_all(ui_bootRoot);
lv_obj_set_width( ui_bootRoot, 220);
lv_obj_set_height( ui_bootRoot, 300);
lv_obj_set_x( ui_bootRoot, -1 );
lv_obj_set_y( ui_bootRoot, 1 );
lv_obj_set_align( ui_bootRoot, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_bootRoot,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_bootRoot, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_remove_flag( ui_bootRoot, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_bootRoot, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_bootRoot, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bootTitle = lv_label_create(ui_bootRoot);
lv_obj_set_width( ui_bootTitle, 197);
lv_obj_set_height( ui_bootTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bootTitle, 12 );
lv_obj_set_y( ui_bootTitle, -316 );
lv_obj_set_align( ui_bootTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_bootTitle,"SmartRV TankPro");
lv_obj_set_style_text_color(ui_bootTitle, lv_color_hex(0xF8F2F2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bootTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bootTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bootTitle, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bootTitle3 = lv_label_create(ui_bootRoot);
lv_obj_set_width( ui_bootTitle3, 200);
lv_obj_set_height( ui_bootTitle3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bootTitle3, 12 );
lv_obj_set_y( ui_bootTitle3, -316 );
lv_obj_set_align( ui_bootTitle3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_bootTitle3,"Choose how this display connects to your system.");
lv_obj_set_style_text_color(ui_bootTitle3, lv_color_hex(0xF8F2F2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bootTitle3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_bootTitle3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bootTitle3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bootwifipanel = lv_obj_create(ui_bootRoot);
lv_obj_set_width( ui_bootwifipanel, 200);
lv_obj_set_height( ui_bootwifipanel, 90);
lv_obj_set_x( ui_bootwifipanel, -50 );
lv_obj_set_y( ui_bootwifipanel, -36 );
lv_obj_set_align( ui_bootwifipanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_bootwifipanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_bootwifipanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_bootwifipanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_bootwifipanel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bootwifipanel, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bootwifipanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bootWifiButton = lv_button_create(ui_bootwifipanel);
lv_obj_set_width( ui_bootWifiButton, 180);
lv_obj_set_height( ui_bootWifiButton, 50);
lv_obj_set_x( ui_bootWifiButton, 0 );
lv_obj_set_y( ui_bootWifiButton, -12 );
lv_obj_set_align( ui_bootWifiButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bootWifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_bootWifiButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifibuttonlabel = lv_label_create(ui_bootWifiButton);
lv_obj_set_width( ui_wifibuttonlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifibuttonlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifibuttonlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifibuttonlabel,"Wi-Fi");
lv_obj_set_style_text_font(ui_wifibuttonlabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifidesclabel = lv_label_create(ui_bootwifipanel);
lv_obj_set_width( ui_wifidesclabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifidesclabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifidesclabel, -21 );
lv_obj_set_y( ui_wifidesclabel, 102 );
lv_obj_set_align( ui_wifidesclabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifidesclabel,"Connect to local wifi");
lv_obj_set_style_text_font(ui_wifidesclabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bootDirectPanel = lv_obj_create(ui_bootRoot);
lv_obj_set_width( ui_bootDirectPanel, 200);
lv_obj_set_height( ui_bootDirectPanel, 90);
lv_obj_set_x( ui_bootDirectPanel, -50 );
lv_obj_set_y( ui_bootDirectPanel, -36 );
lv_obj_set_align( ui_bootDirectPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_bootDirectPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_bootDirectPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_bootDirectPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_bootDirectPanel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bootDirectPanel, lv_color_hex(0xCCC5C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bootDirectPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bootDirectButton = lv_button_create(ui_bootDirectPanel);
lv_obj_set_width( ui_bootDirectButton, 180);
lv_obj_set_height( ui_bootDirectButton, 50);
lv_obj_set_x( ui_bootDirectButton, 0 );
lv_obj_set_y( ui_bootDirectButton, -12 );
lv_obj_set_align( ui_bootDirectButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bootDirectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_bootDirectButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_bootDirectLabel = lv_label_create(ui_bootDirectButton);
lv_obj_set_width( ui_bootDirectLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bootDirectLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_bootDirectLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_bootDirectLabel,"Direct");
lv_obj_set_style_text_font(ui_bootDirectLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_directdesclabel = lv_label_create(ui_bootDirectPanel);
lv_obj_set_width( ui_directdesclabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_directdesclabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_directdesclabel, -21 );
lv_obj_set_y( ui_directdesclabel, 102 );
lv_obj_set_align( ui_directdesclabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_directdesclabel,"Connect direct to controller");
lv_obj_set_style_text_font(ui_directdesclabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bootFirmwareLabel = lv_label_create(ui_bootRoot);
lv_obj_set_width( ui_bootFirmwareLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bootFirmwareLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bootFirmwareLabel, 59 );
lv_obj_set_y( ui_bootFirmwareLabel, 3 );
lv_obj_set_align( ui_bootFirmwareLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_bootFirmwareLabel,"versiontest");
ui_object_set_themeable_style_property(ui_bootFirmwareLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_bootFirmwareLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_align(ui_bootFirmwareLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bootFirmwareLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_overlayBootWifi = lv_obj_create(ui_boot);
lv_obj_remove_style_all(ui_overlayBootWifi);
lv_obj_set_width( ui_overlayBootWifi, 240);
lv_obj_set_height( ui_overlayBootWifi, 295);
lv_obj_set_align( ui_overlayBootWifi, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_overlayBootWifi,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_overlayBootWifi, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_overlayBootWifi, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_overlayBootWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_overlayBootWifi, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_black);
ui_object_set_themeable_style_property(ui_overlayBootWifi, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_black);
lv_obj_set_style_blend_mode(ui_overlayBootWifi, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_overlayBootWifi, 240, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_overlayBootWifi, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_overlayBootWifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_popupbootwifi = lv_obj_create(ui_overlayBootWifi);
lv_obj_remove_style_all(ui_popupbootwifi);
lv_obj_set_width( ui_popupbootwifi, 220);
lv_obj_set_height( ui_popupbootwifi, 86);
lv_obj_set_x( ui_popupbootwifi, 1 );
lv_obj_set_y( ui_popupbootwifi, -53 );
lv_obj_set_align( ui_popupbootwifi, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_popupbootwifi,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_popupbootwifi, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_popupbootwifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_popupbootwifi, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_popupbootwifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_popupbootwifi, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblbootwifititle = lv_label_create(ui_popupbootwifi);
lv_obj_set_width( ui_lblbootwifititle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblbootwifititle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblbootwifititle, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblbootwifititle,"Wi-Fi Setup");
ui_object_set_themeable_style_property(ui_lblbootwifititle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lblbootwifititle, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_font(ui_lblbootwifititle, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblbootwifidesc = lv_label_create(ui_popupbootwifi);
lv_obj_set_width( ui_lblbootwifidesc, lv_pct(100));
lv_obj_set_height( ui_lblbootwifidesc, lv_pct(49));
lv_obj_set_align( ui_lblbootwifidesc, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblbootwifidesc,"Connect to this access point ");
ui_object_set_themeable_style_property(ui_lblbootwifidesc, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_lblbootwifidesc, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_align(ui_lblbootwifidesc, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblbootwifidesc, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ssid_container = lv_obj_create(ui_overlayBootWifi);
lv_obj_remove_style_all(ui_ssid_container);
lv_obj_set_width( ui_ssid_container, 220);
lv_obj_set_height( ui_ssid_container, 50);
lv_obj_set_align( ui_ssid_container, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ssid_container,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ssid_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_ssid_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_ssid_container, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_ssid_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_ssid_container);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"SSID");
ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_decor(ui_Label4, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bootWifissid = lv_label_create(ui_ssid_container);
lv_obj_set_width( ui_bootWifissid, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bootWifissid, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_bootWifissid, LV_ALIGN_CENTER );
lv_label_set_text(ui_bootWifissid,"test");
ui_object_set_themeable_style_property(ui_bootWifissid, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_bootWifissid, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);

ui_pwd_container1 = lv_obj_create(ui_overlayBootWifi);
lv_obj_remove_style_all(ui_pwd_container1);
lv_obj_set_width( ui_pwd_container1, 220);
lv_obj_set_height( ui_pwd_container1, 45);
lv_obj_set_align( ui_pwd_container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_pwd_container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_pwd_container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_pwd_container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_pwd_container1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_pwd_container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_pwd_container1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Password");
ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_decor(ui_Label9, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bootWifipass = lv_label_create(ui_pwd_container1);
lv_obj_set_width( ui_bootWifipass, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bootWifipass, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_bootWifipass, LV_ALIGN_CENTER );
lv_label_set_text(ui_bootWifipass,"test");
ui_object_set_themeable_style_property(ui_bootWifipass, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_bootWifipass, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);

ui_Label10 = lv_label_create(ui_overlayBootWifi);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 2 );
lv_obj_set_y( ui_Label10, -24 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"-----------------------------------------\nOpen http://192.168.4.1\nFollow Wi-Fi Setup");
ui_object_set_themeable_style_property(ui_Label10, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_text);
ui_object_set_themeable_style_property(ui_Label10, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_text);
lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_overlayBootWifi);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 220);
lv_obj_set_height( ui_Container4, 50);
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container4, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonBootWifiBack = lv_button_create(ui_Container4);
lv_obj_set_width( ui_buttonBootWifiBack, 164);
lv_obj_set_height( ui_buttonBootWifiBack, 40);
lv_obj_set_align( ui_buttonBootWifiBack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttonBootWifiBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonBootWifiBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_buttonBootWifiBack);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Back");

lv_obj_add_event_cb(ui_bootWifiButton, ui_event_bootWifiButton, LV_EVENT_ALL, NULL);
uic_boot = ui_boot;
uic_bootRoot = ui_bootRoot;
uic_bootTitle = ui_bootTitle;
uic_bootTitle3 = ui_bootTitle3;
uic_bootwifipanel = ui_bootwifipanel;
uic_bootWifiButton = ui_bootWifiButton;
uic_wifibuttonlabel = ui_wifibuttonlabel;
uic_wifilabel = ui_wifidesclabel;
uic_bootDirectPanel = ui_bootDirectPanel;
uic_bootDirectButton = ui_bootDirectButton;
uic_bootDirectLabel = ui_bootDirectLabel;
uic_directlabel = ui_directdesclabel;

}

void ui_boot_screen_destroy(void)
{
   if (ui_boot) lv_obj_del(ui_boot);

// NULL screen variables
uic_boot= NULL;
ui_boot= NULL;
uic_bootRoot= NULL;
ui_bootRoot= NULL;
uic_bootTitle= NULL;
ui_bootTitle= NULL;
uic_bootTitle3= NULL;
ui_bootTitle3= NULL;
uic_bootwifipanel= NULL;
ui_bootwifipanel= NULL;
uic_bootWifiButton= NULL;
ui_bootWifiButton= NULL;
uic_wifibuttonlabel= NULL;
ui_wifibuttonlabel= NULL;
uic_wifilabel= NULL;
ui_wifidesclabel= NULL;
uic_bootDirectPanel= NULL;
ui_bootDirectPanel= NULL;
uic_bootDirectButton= NULL;
ui_bootDirectButton= NULL;
uic_bootDirectLabel= NULL;
ui_bootDirectLabel= NULL;
uic_directlabel= NULL;
ui_directdesclabel= NULL;
ui_bootFirmwareLabel= NULL;
ui_overlayBootWifi= NULL;
ui_popupbootwifi= NULL;
ui_lblbootwifititle= NULL;
ui_lblbootwifidesc= NULL;
ui_ssid_container= NULL;
ui_Label4= NULL;
ui_bootWifissid= NULL;
ui_pwd_container1= NULL;
ui_Label9= NULL;
ui_bootWifipass= NULL;
ui_Label10= NULL;
ui_Container4= NULL;
ui_buttonBootWifiBack= NULL;
ui_Label11= NULL;

}
