// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_CYDSETTINGS_H
#define UI_CYDSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_cydsettings
extern void ui_cydsettings_screen_init(void);
extern void ui_cydsettings_screen_destroy(void);
extern lv_obj_t *ui_cydsettings;
extern lv_obj_t *ui_CYDSettingsRoot;
extern lv_obj_t *ui_cydsettingsheader;
extern lv_obj_t *ui_Label33;
extern lv_obj_t *ui_cydsettingsBackButton;
extern lv_obj_t *ui_cydsettingspanel;
extern lv_obj_t *ui_cydsettingsscroll;
extern lv_obj_t *ui_cydsettitles;
extern lv_obj_t *ui_Label35;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label37;
extern lv_obj_t *ui_Label82;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_contset;
extern lv_obj_t *ui_cydBrightnessSlider;
extern lv_obj_t *ui_cydTimeout;
extern lv_obj_t *ui_cydTheme;
extern lv_obj_t *ui_cydUnits;
extern lv_obj_t *ui_cydDiagnosticButton;
extern lv_obj_t *ui_cydsettingsDiagnosticOverlay;
extern lv_obj_t *ui_cyddiagroot;
extern lv_obj_t *ui_cydsettingslabels;
extern lv_obj_t *ui_Label93;
extern lv_obj_t *ui_Label84;
extern lv_obj_t *ui_Label85;
extern lv_obj_t *ui_Label86;
extern lv_obj_t *ui_Label87;
extern lv_obj_t *ui_Label88;
extern lv_obj_t *ui_Label89;
extern lv_obj_t *ui_Label90;
extern lv_obj_t *ui_cydsettingsdiagdata;
extern lv_obj_t *ui_cydsettingsdiagoverlayIP;
extern lv_obj_t *ui_cydsettingsdiagoverlayID;
extern lv_obj_t *ui_cydsettingsdiagoverlayMAC;
extern lv_obj_t *ui_cydsettingsdiagoverlayWifiStatus;
extern lv_obj_t *ui_cydsettingsdiagoverlayWifiSignal;
extern lv_obj_t *ui_cydsettingsdiagoverlayUptime;
extern lv_obj_t *ui_cydsettingsdiagoverlayFreshConnected;
extern lv_obj_t *ui_cydsettingsdiagoverlayWasteConnected;
extern lv_obj_t *ui_cydsettingDiagnosticOverlayBackButton;
extern lv_obj_t *ui_Label91;
extern lv_obj_t *ui_cydsettingsFactoryResetConfirmationOverlay;
extern lv_obj_t *ui_cydsettingsResetButton;
extern lv_obj_t *ui_Label96;
extern lv_obj_t *ui_Label92;
extern lv_obj_t *ui_Label94;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_cydsettingsResetBackButton;
extern lv_obj_t *ui_Label95;
extern lv_obj_t *ui_cydFirmwareLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

