// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Watertanksensor

#ifndef UI_WASTEFAULTS_H
#define UI_WASTEFAULTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wastefaults
extern void ui_wastefaults_screen_init(void);
extern void ui_wastefaults_screen_destroy(void);
extern lv_obj_t *ui_wastefaults;
extern lv_obj_t *ui_greyFaultPopupOverlay2;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_wastefaultscard;
extern lv_obj_t *ui_wastefaultsCodeLabel;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_wastefaultsdescription;
extern lv_obj_t *ui_wastefaultsCodeDescription;
extern lv_obj_t *ui_greyPopuputtons2;
extern lv_obj_t *ui_wastefaultsBackButton;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_wastefaultsClearButton;
extern lv_obj_t *ui_Label22;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

